import { AvailableAction, Action } from "../api/types.js";

/**
 * Normalizes common human shortcut aliases to standard command strings.
 */
export function normalizeCommandString(input: string): string {
  const str = input.trim().toLowerCase();
  if (str === "n") return "go north";
  if (str === "s") return "go south";
  if (str === "e") return "go east";
  if (str === "w") return "go west";
  if (str === "u") return "go up";
  if (str === "d") return "go down";
  if (str === "i") return "inventory";
  if (str === "inv") return "inventory";
  if (str === "l") return "look";
  return str;
}

// Synonyms mapping for user verbs to canonical categories.
const VERB_CATEGORIES: Record<string, string[]> = {
  // Move
  go: ["MOVE"],
  move: ["MOVE"],
  walk: ["MOVE"],
  travel: ["MOVE"],
  run: ["MOVE"],
  step: ["MOVE"],
  north: ["MOVE"],
  south: ["MOVE"],
  east: ["MOVE"],
  west: ["MOVE"],
  up: ["MOVE"],
  down: ["MOVE"],
  n: ["MOVE"],
  s: ["MOVE"],
  e: ["MOVE"],
  w: ["MOVE"],
  u: ["MOVE"],
  d: ["MOVE"],
  enter: ["MOVE"],
  exit: ["MOVE", "ASK"],
  cross: ["MOVE"],
  jump: ["MOVE"],
  leap: ["MOVE"],
  ascend: ["MOVE"],
  descend: ["MOVE"],
  pass: ["MOVE", "GIVE", "ASK"],
  traverse: ["MOVE"],
  swim: ["MOVE"],
  advance: ["MOVE"],
  head: ["MOVE"],
  proceed: ["MOVE"],
  journey: ["MOVE"],
  sail: ["MOVE"],
  sneak: ["MOVE"],
  crawl: ["MOVE"],
  hop: ["MOVE"],
  skip: ["MOVE"],
  "go to": ["MOVE"],
  "walk to": ["MOVE"],
  "run to": ["MOVE"],
  "move to": ["MOVE"],
  "climb up": ["MOVE"],
  "climb down": ["MOVE"],
  "climb on": ["MOVE"],
  "scale up": ["MOVE"],
  "go up": ["MOVE"],
  "go down": ["MOVE"],
  "go inside": ["MOVE"],
  "go outside": ["MOVE"],
  "head north": ["MOVE"],
  "head south": ["MOVE"],
  "head east": ["MOVE"],
  "head west": ["MOVE"],
  "head up": ["MOVE"],
  "head down": ["MOVE"],
  "climb up to": ["MOVE"],
  "scramble up": ["MOVE"],
  "climb down to": ["MOVE"],
  "ascend to": ["MOVE"],
  "descend to": ["MOVE"],
  "pass through": ["MOVE"],
  "walk through": ["MOVE"],
  "step through": ["MOVE"],
  "crawl through": ["MOVE"],
  "climb down well": ["MOVE", "USE"],
  "go down well": ["MOVE"],
  "descend down to": ["MOVE"],
  "descend down": ["MOVE"],
  "descend into": ["MOVE"],
  "go down to": ["MOVE"],
  "go up to": ["MOVE"],
  "walk down to": ["MOVE"],
  "walk up to": ["MOVE"],
  "run down to": ["MOVE"],
  "run up to": ["MOVE"],
  "go towards": ["MOVE"],
  "walk towards": ["MOVE"],
  "run towards": ["MOVE"],
  "head towards": ["MOVE"],
  "go back": ["MOVE"],
  "go back to": ["MOVE"],
  "climb through": ["MOVE"],
  "squeeze through": ["MOVE"],
  "slip through": ["MOVE"],
  "climb to": ["MOVE"],
  wander: ["MOVE"],
  stroll: ["MOVE"],
  march: ["MOVE"],
  jog: ["MOVE"],
  hike: ["MOVE"],
  dash: ["MOVE"],
  bolt: ["MOVE", "CLOSE"],
  backtrack: ["MOVE"],

  // Climb can be movement (climb up) or interaction (climb wall)
  climb: ["MOVE", "USE"],
  scale: ["MOVE", "USE"],

  look: ["LOOK_INSPECT"],
  inspect: ["LOOK_INSPECT"],
  examine: ["LOOK_INSPECT"],
  x: ["LOOK_INSPECT"],
  view: ["LOOK_INSPECT"],
  search: ["LOOK_INSPECT"],
  read: ["LOOK_INSPECT"],
  peer: ["LOOK_INSPECT"],
  stare: ["LOOK_INSPECT"],
  observe: ["LOOK_INSPECT"],
  scan: ["LOOK_INSPECT"],
  check: ["LOOK_INSPECT", "ASK"],
  study: ["LOOK_INSPECT"],
  gaze: ["LOOK_INSPECT"],
  glance: ["LOOK_INSPECT"],
  scrutinize: ["LOOK_INSPECT"],
  watch: ["LOOK_INSPECT"],
  explore: ["LOOK_INSPECT"],
  find: ["LOOK_INSPECT"],
  seek: ["LOOK_INSPECT"],
  "look at": ["LOOK_INSPECT"],
  "check out": ["LOOK_INSPECT", "ASK"],
  "gaze at": ["LOOK_INSPECT"],
  "glance at": ["LOOK_INSPECT"],
  "stare at": ["LOOK_INSPECT"],
  "peer into": ["LOOK_INSPECT"],
  "peer at": ["LOOK_INSPECT"],
  "look under": ["LOOK_INSPECT"],
  "look inside": ["LOOK_INSPECT"],
  "look in": ["LOOK_INSPECT"],
  "look through": ["LOOK_INSPECT"],
  "inspect closely": ["LOOK_INSPECT"],
  "take a look at": ["LOOK_INSPECT"],
  "gaze upon": ["LOOK_INSPECT"],
  "glance upon": ["LOOK_INSPECT"],
  "stare upon": ["LOOK_INSPECT"],
  "peer inside of": ["LOOK_INSPECT"],
  "peer into of": ["LOOK_INSPECT"],
  "peer at of": ["LOOK_INSPECT"],
  "look in to": ["LOOK_INSPECT"],
  "look inside of": ["LOOK_INSPECT"],
  "look closely at": ["LOOK_INSPECT"],
  "look closely": ["LOOK_INSPECT"],
  "take look": ["LOOK_INSPECT"],
  "examine closely": ["LOOK_INSPECT"],
  "read book": ["LOOK_INSPECT"],
  "read paper": ["LOOK_INSPECT"],
  "inspect item": ["LOOK_INSPECT"],
  "examine object": ["LOOK_INSPECT"],
  "peer down into": ["LOOK_INSPECT"],
  "peer through": ["LOOK_INSPECT"],
  "look down well": ["LOOK_INSPECT"],
  "look down into": ["LOOK_INSPECT"],
  "look down": ["LOOK_INSPECT"],
  "look up at": ["LOOK_INSPECT"],
  "look up": ["LOOK_INSPECT"],
  "peer down": ["LOOK_INSPECT"],
  "gaze down": ["LOOK_INSPECT"],
  "gaze up": ["LOOK_INSPECT"],
  "look over": ["LOOK_INSPECT"],
  "read notes": ["LOOK_INSPECT"],
  "read sign": ["LOOK_INSPECT"],
  "read letter": ["LOOK_INSPECT"],
  "read inscription": ["LOOK_INSPECT"],
  "read writing": ["LOOK_INSPECT"],
  "read text": ["LOOK_INSPECT"],
  investigate: ["LOOK_INSPECT"],
  appraise: ["LOOK_INSPECT"],
  survey: ["LOOK_INSPECT"],
  detect: ["LOOK_INSPECT"],
  discern: ["LOOK_INSPECT"],
  spy: ["LOOK_INSPECT"],
  spot: ["LOOK_INSPECT"],

  take: ["TAKE"],
  get: ["TAKE"],
  grab: ["TAKE"],
  pick: ["TAKE", "UNLOCK"],
  collect: ["TAKE"],
  acquire: ["TAKE"],
  steal: ["TAKE"],
  pocket: ["TAKE"],
  gather: ["TAKE"],
  lift: ["TAKE"],
  snatch: ["TAKE"],
  retrieve: ["TAKE"],
  secure: ["TAKE"],
  loot: ["TAKE"],
  plunder: ["TAKE"],
  rob: ["TAKE"],
  pilfer: ["TAKE"],
  hoist: ["TAKE"],
  capture: ["TAKE"],
  receive: ["TAKE"],
  seize: ["TAKE"],
  "pick up": ["TAKE"],
  "gather up": ["TAKE"],
  "scoop up": ["TAKE"],
  "take up": ["TAKE"],
  scoop: ["TAKE"],
  harvest: ["TAKE"],
  extract: ["TAKE"],
  salvage: ["TAKE"],
  claim: ["TAKE"],
  "take away": ["TAKE"],
  draw: ["TAKE"],
  withdraw: ["TAKE", "FLEE"],
  remove: ["TAKE"],
  "take hold of": ["TAKE"],
  "grab hold of": ["TAKE"],
  "lift up": ["TAKE"],
  "remove item": ["TAKE"],
  pickup: ["TAKE"],
  slip: ["TAKE"],
  add: ["TAKE"],
  "slip into pocket": ["TAKE"],
  "put in pocket": ["TAKE"],
  "put in bag": ["TAKE"],
  "add to inventory": ["TAKE"],
  "hoist up": ["TAKE"],
  dislodge: ["TAKE"],
  unearth: ["TAKE", "USE"],
  confiscate: ["TAKE"],

  drop: ["DROP"],
  discard: ["DROP"],
  throw: ["DROP"],
  put: ["DROP"],
  place: ["DROP"],
  dump: ["DROP"],
  toss: ["DROP"],
  abandon: ["DROP"],
  "put down": ["DROP"],
  "throw away": ["DROP"],
  "drop off": ["DROP"],
  "leave behind": ["DROP"],
  "toss out": ["DROP"],
  leave: ["DROP", "ASK"],
  "discard item": ["DROP"],
  set: ["DROP"],
  lay: ["DROP"],
  "place down": ["DROP"],
  "set down": ["DROP"],
  "lay down": ["DROP"],
  "toss away": ["DROP"],
  "fling away": ["DROP"],
  "cast away": ["DROP"],
  "cast off": ["DROP"],
  jettison: ["DROP"],
  shed: ["DROP"],

  open: ["OPEN"],
  close: ["CLOSE"],
  shut: ["CLOSE"],
  unseal: ["OPEN"],
  reveal: ["OPEN"],
  crack: ["OPEN"],
  seal: ["CLOSE"],
  lock: ["CLOSE"],
  "crack open": ["OPEN"],
  "pry open": ["OPEN"],
  "swing open": ["OPEN"],
  "open up": ["OPEN"],
  "shut close": ["CLOSE"],
  "close up": ["CLOSE"],
  "shut up": ["CLOSE"],
  force: ["OPEN"],
  pop: ["OPEN"],
  unlatch: ["OPEN"],
  "force open": ["OPEN"],
  "open lid of": ["OPEN"],
  "open lid": ["OPEN"],
  "slide lid of": ["OPEN", "USE"],
  "slide lid": ["OPEN", "USE"],
  "lift lid of": ["OPEN"],
  "lift lid": ["OPEN"],
  "shut lid of": ["CLOSE"],
  "shut lid": ["CLOSE"],
  "close lid of": ["CLOSE"],
  "close lid": ["CLOSE"],
  unzip: ["OPEN"],
  unfold: ["OPEN"],
  unwrap: ["OPEN"],
  uncover: ["OPEN"],
  expose: ["OPEN"],
  latch: ["CLOSE"],
  zip: ["CLOSE"],
  fold: ["CLOSE"],
  wrap: ["CLOSE", "USE"],
  cover: ["CLOSE"],
  conceal: ["CLOSE"],

  unlock: ["UNLOCK", "USE"],
  unbolt: ["UNLOCK", "USE"],
  key: ["UNLOCK", "USE"],
  deactivate: ["UNLOCK", "USE"],
  bypass: ["UNLOCK", "USE"],
  "pick lock": ["UNLOCK", "USE"],
  "unlock with": ["UNLOCK", "USE"],
  "unlock lock": ["UNLOCK", "USE"],
  "pick lock on": ["UNLOCK", "USE"],
  "use key on": ["UNLOCK", "USE"],
  "use key to unlock": ["UNLOCK", "USE"],
  "use key to open": ["UNLOCK", "USE"],
  "use key": ["UNLOCK", "USE"],
  "unlock gate with": ["UNLOCK", "USE"],
  "unlock chest with": ["UNLOCK", "USE"],
  unfasten: ["UNLOCK", "USE"],
  release: ["UNLOCK", "USE"],
  disengage: ["UNLOCK", "USE"],
  unshackle: ["UNLOCK", "USE"],
  "unlock chest": ["UNLOCK", "USE"],
  "unlock door": ["UNLOCK", "USE"],

  use: ["USE"],
  dig: ["USE"],
  excavate: ["USE"],
  shovel: ["USE"],
  pull: ["USE"],
  push: ["USE"],
  press: ["USE"],
  flip: ["USE"],
  turn: ["USE"],
  activate: ["USE"],
  trigger: ["USE"],
  raise: ["USE"],
  lower: ["USE"],
  tie: ["USE"],
  attach: ["USE"],
  combine: ["USE"],
  craft: ["USE"],
  meld: ["USE"],
  forge: ["USE"],
  apply: ["USE"],
  insert: ["USE"],
  slide: ["USE"],
  click: ["USE"],
  toggle: ["USE"],
  touch: ["USE"],
  drag: ["USE"],
  wield: ["USE"],
  equip: ["USE"],
  consume: ["USE"],
  drink: ["USE"],
  eat: ["USE"],
  blow: ["USE"],
  play: ["USE"],
  strike: ["USE", "FIGHT"],
  "use item with": ["USE"],
  "use item on": ["USE"],
  "activate mechanism": ["USE"],
  "pull lever": ["USE"],
  "push button": ["USE"],
  "flip switch": ["USE"],
  "turn valve": ["USE"],
  "strike match": ["USE"],
  "light torch": ["USE"],
  "light up": ["USE"],
  light: ["USE"],
  disarm: ["USE"],
  defuse: ["USE"],
  disable: ["USE"],
  "disarm trap on": ["USE"],
  "disarm trap": ["USE"],
  "disable trap on": ["USE"],
  "disable trap": ["USE"],
  "deactivate trap on": ["USE"],
  "deactivate trap": ["USE"],
  fasten: ["USE"],
  bind: ["USE"],
  "tie rope to": ["USE"],
  "attach rope to": ["USE"],
  "fasten rope to": ["USE"],
  "interact with": ["USE"],
  "drink from": ["USE"],
  "sip from": ["USE"],
  "eat up": ["USE"],
  operate: ["USE"],
  manipulate: ["USE"],
  employ: ["USE"],
  utilize: ["USE"],
  handle: ["USE"],
  interact: ["USE"],
  cut: ["USE"],
  slice: ["USE"],
  chop: ["USE"],
  tear: ["USE"],
  rip: ["USE"],
  burn: ["USE"],
  ignite: ["USE"],
  kindle: ["USE"],
  extinguish: ["USE"],
  douse: ["USE"],
  snuff: ["USE"],
  gulp: ["USE"],
  swallow: ["USE"],
  devour: ["USE"],
  pour: ["USE"],
  splash: ["USE"],
  sprinkle: ["USE"],

  // Talk/Ask
  talk: ["TALK", "ASK"],
  speak: ["TALK", "ASK"],
  greet: ["TALK", "ASK"],
  chat: ["TALK", "ASK"],
  ask: ["ASK"],
  tell: ["ASK"],
  say: ["ASK"],
  converse: ["TALK", "ASK"],
  question: ["TALK", "ASK"],
  discuss: ["TALK", "ASK"],
  query: ["ASK"],
  demand: ["ASK"],
  interrogate: ["ASK"],
  interview: ["TALK", "ASK"],
  hail: ["TALK", "ASK"],
  whisper: ["TALK", "ASK"],
  "talk to": ["TALK", "ASK"],
  "speak to": ["TALK", "ASK"],
  "converse with": ["TALK", "ASK"],
  "chat with": ["TALK", "ASK"],
  "speak with": ["TALK", "ASK"],
  "talk with": ["TALK", "ASK"],
  "ask about": ["ASK"],
  "discuss with": ["TALK", "ASK"],
  "query about": ["ASK"],
  "talk with npc": ["TALK", "ASK"],
  "question npc": ["TALK", "ASK"],
  inquire: ["TALK", "ASK"],
  request: ["TALK", "ASK"],
  "inquire about": ["ASK"],
  "inquire for": ["ASK"],
  "request access to": ["ASK"],
  negotiate: ["TALK", "ASK"],
  "negotiate with": ["TALK", "ASK"],
  "parley with": ["TALK", "ASK"],
  "consult with": ["TALK", "ASK"],
  "ask npc about": ["ASK"],
  "ask npc for": ["ASK"],
  "shout to": ["TALK", "ASK"],
  "yell to": ["TALK", "ASK"],
  "call to": ["TALK", "ASK"],
  beg: ["TALK", "ASK"],
  plead: ["TALK", "ASK"],
  parley: ["TALK", "ASK"],
  consult: ["TALK", "ASK"],

  // Give
  give: ["GIVE", "ASK"],
  hand: ["GIVE", "ASK"],
  deliver: ["GIVE"],
  offer: ["GIVE"],
  present: ["GIVE"],
  submit: ["GIVE"],
  pay: ["GIVE"],
  trade: ["GIVE"],
  gift: ["GIVE"],
  donate: ["GIVE"],
  bribe: ["GIVE"],
  "hand over": ["GIVE"],
  "give to": ["GIVE", "ASK"],
  "give item to": ["GIVE"],
  "hand to": ["GIVE", "ASK"],
  "hand item to": ["GIVE"],
  "trade with": ["GIVE"],
  "trade item with": ["GIVE"],
  "bribe with": ["GIVE"],
  "bribe npc with": ["GIVE"],
  "present to": ["GIVE"],
  "offer to": ["GIVE"],
  "deliver to": ["GIVE"],
  "pay npc": ["GIVE"],
  "bribe npc": ["GIVE"],
  bequeath: ["GIVE"],

  // Inventory
  inventory: ["INVENTORY"],
  items: ["INVENTORY"],
  inv: ["INVENTORY"],
  bag: ["INVENTORY", "TAKE"],
  pack: ["INVENTORY"],
  carrying: ["INVENTORY"],
  equipment: ["INVENTORY"],
  gear: ["INVENTORY"],
  pockets: ["INVENTORY"],
  "check inventory": ["INVENTORY"],
  "show inventory": ["INVENTORY"],
  "look at inventory": ["INVENTORY"],
  "view inventory": ["INVENTORY"],
  "list inventory": ["INVENTORY"],
  "check bags": ["INVENTORY"],
  "check pack": ["INVENTORY"],
  "check pockets": ["INVENTORY"],
  "show items": ["INVENTORY"],
  "check items": ["INVENTORY"],
  "list items": ["INVENTORY"],
  "view items": ["INVENTORY"],
  "my items": ["INVENTORY"],
  "check bag": ["INVENTORY"],
  "check backpack": ["INVENTORY"],
  "view bag": ["INVENTORY"],
  "view pack": ["INVENTORY"],
  backpack: ["INVENTORY"],

  fight: ["FIGHT"],
  attack: ["FIGHT"],
  kill: ["FIGHT"],
  slay: ["FIGHT"],
  hit: ["FIGHT"],
  battle: ["FIGHT"],
  slash: ["FIGHT"],
  punch: ["FIGHT"],
  kick: ["FIGHT"],
  shoot: ["FIGHT"],
  fire: ["FIGHT"],
  engage: ["FIGHT"],
  smash: ["USE", "FIGHT"],
  beat: ["FIGHT"],
  bash: ["FIGHT"],
  stab: ["FIGHT"],
  confront: ["FIGHT"],
  cast: ["CAST"],
  spell: ["CAST"],
  "cast spell": ["CAST"],
  channel: ["CAST"],
  invoke: ["CAST"],
  summon: ["CAST"],
  "use magic": ["CAST"],
  flee: ["FLEE"],
  escape: ["FLEE"],
  "run away": ["FLEE"],
  retreat: ["FLEE"],
  "attack npc with": ["FIGHT"],
  "fight npc with": ["FIGHT"],
  "kill npc with": ["FIGHT"],
  "slay npc with": ["FIGHT"],
  "strike npc with": ["FIGHT"],
  "hit npc with": ["FIGHT"],
  "strike with": ["FIGHT"],
  "hit with": ["FIGHT"],
  "slash with": ["FIGHT"],
  "stab with": ["FIGHT"],
  "engage in combat with": ["FIGHT"],
  "engage combat with": ["FIGHT"],
  "engage in battle with": ["FIGHT"],
  "engage battle with": ["FIGHT"],
  execute: ["FIGHT"],
  destroy: ["USE", "FIGHT"],
  combat: ["FIGHT"],

  // Cast Spell
  "cast spell on": ["CAST"],
  "channel spell on": ["CAST"],
  "use magic on": ["CAST"],
  "cast magic on": ["CAST"],
  "cast fireball on": ["CAST"],
  "cast fireball": ["CAST"],
  "cast heal on": ["CAST"],
  "cast heal": ["CAST"],
  "cast freeze on": ["CAST"],
  "cast freeze": ["CAST"],
  "cast lightning on": ["CAST"],
  "cast lightning": ["CAST"],
  "cast poison on": ["CAST"],
  "cast poison": ["CAST"],
  "channel magic on": ["CAST"],

  // Flee
  "run away from": ["FLEE"],
  "escape from": ["FLEE"],
  "retreat from": ["FLEE"],
  "withdraw from": ["FLEE"],
  "flee from": ["FLEE"],

  // Trade
  buy: ["BUY"],
  purchase: ["BUY"],
  sell: ["SELL"],
  vendor: ["SELL"],
  "trade for": ["BUY"],
  "acquire from": ["BUY"],
  "sell to": ["SELL"],
  "buy item from": ["BUY"],
  "buy from": ["BUY"],
  "purchase from": ["BUY"],
  "purchase item from": ["BUY"],
  "sell item to": ["SELL"],

  accept: ["ASK"],
  agree: ["ASK"],
  report: ["ASK"],
  complete: ["ASK"],
  finish: ["ASK"],
  choose: ["ASK"],
  select: ["ASK"],
  bye: ["ASK"],
  goodbye: ["ASK"],
  help: ["ASK"],
  return: ["ASK"],
  "turn in": ["ASK"],
  "report on": ["ASK"],
  "ask for": ["ASK"],
  "agree to": ["ASK"],
  "say goodbye": ["ASK"],

  // Additional synonyms for natural parser commands
  break: ["USE", "FIGHT"],
  shatter: ["USE", "FIGHT"],
  wreck: ["USE", "FIGHT"],
  demolish: ["USE", "FIGHT"],
  decipher: ["LOOK_INSPECT"],
  translate: ["LOOK_INSPECT"],
  rummage: ["LOOK_INSPECT", "TAKE"],
  scavenge: ["LOOK_INSPECT", "TAKE"],
  transfer: ["GIVE"],
  address: ["TALK", "ASK"],
  beckon: ["TALK", "ASK"],
  mount: ["MOVE", "USE"],
  dismount: ["MOVE", "USE"],
  board: ["MOVE", "USE"],
  peek: ["LOOK_INSPECT"],
  "peek inside": ["LOOK_INSPECT"],
  "peek into": ["LOOK_INSPECT"],
  wear: ["USE"],
  "put on": ["USE"],
  "take off": ["USE"],
  hasten: ["MOVE"],
  sprint: ["MOVE"],
  scurry: ["MOVE"],
  hurry: ["MOVE"],
  "travel to": ["MOVE"],
  "head to": ["MOVE"],
  "go to the": ["MOVE"],
  "walk to the": ["MOVE"],
  "run to the": ["MOVE"],
  "head to the": ["MOVE"],
  "move to the": ["MOVE"],
  peruse: ["LOOK_INSPECT"],
  "read through": ["LOOK_INSPECT"],
  "glance over": ["LOOK_INSPECT"],
  "check on": ["LOOK_INSPECT"],
  "take the": ["TAKE"],
  "grab the": ["TAKE"],
  "snatch the": ["TAKE"],
  "retrieve the": ["TAKE"],
  "collect the": ["TAKE"],
  "pick up the": ["TAKE"],
  "use the": ["USE"],
  "pull the": ["USE"],
  "push the": ["USE"],
  "press the": ["USE"],
  "flip the": ["USE"],
  "turn the": ["USE"],
  "interact with the": ["USE"],
  "talk to the": ["TALK", "ASK"],
  "speak with the": ["TALK", "ASK"],
  "speak to the": ["TALK", "ASK"],
  "talk with the": ["TALK", "ASK"],
  "ask the": ["ASK"],
  "fight the": ["FIGHT"],
  "attack the": ["FIGHT"],
  "kill the": ["FIGHT"],
  "slay the": ["FIGHT"],
  "strike the": ["FIGHT"],
  "strike down": ["FIGHT"],
  "beat down": ["FIGHT"],
  "engage with": ["FIGHT"],
  "go down the": ["MOVE"],
  "go up the": ["MOVE"],
  "climb up the": ["MOVE"],
  "climb down the": ["MOVE"],
  "scale up the": ["MOVE"],
  "climb on the": ["MOVE"],
  "unlock the": ["UNLOCK", "USE"],
  "unlock chest with the": ["UNLOCK", "USE"],
  "unlock gate with the": ["UNLOCK", "USE"],
  "use key on the": ["UNLOCK", "USE"],

  // Even more synonyms for Task-F24 expansion
  scramble: ["MOVE", "USE"],
  scamper: ["MOVE"],
  stride: ["MOVE"],
  "go in": ["MOVE"],
  "walk in": ["MOVE"],
  "run in": ["MOVE"],
  "step in": ["MOVE"],
  "climb in": ["MOVE"],
  "crawl in": ["MOVE"],
  "enter inside": ["MOVE"],
  "head inside": ["MOVE"],
  "step inside": ["MOVE"],
  "walk inside": ["MOVE"],
  "run inside": ["MOVE"],
  "climb inside": ["MOVE"],
  "move inside": ["MOVE"],
  "exit outside": ["MOVE"],
  "step outside": ["MOVE"],
  "walk outside": ["MOVE"],
  "run outside": ["MOVE"],
  "climb outside": ["MOVE"],
  "move outside": ["MOVE"],
  "go northward": ["MOVE"],
  "go southward": ["MOVE"],
  "go eastward": ["MOVE"],
  "go westward": ["MOVE"],
  "walk northward": ["MOVE"],
  "walk southward": ["MOVE"],
  "walk eastward": ["MOVE"],
  "walk westward": ["MOVE"],
  "run northward": ["MOVE"],
  "run southward": ["MOVE"],
  "run eastward": ["MOVE"],
  "run westward": ["MOVE"],
  "head northward": ["MOVE"],
  "head southward": ["MOVE"],
  "head eastward": ["MOVE"],
  "head westward": ["MOVE"],
  "go through": ["MOVE"],
  "run through": ["MOVE"],
  glimpse: ["LOOK_INSPECT"],
  behold: ["LOOK_INSPECT"],
  regard: ["LOOK_INSPECT"],
  eyeball: ["LOOK_INSPECT"],
  "gaze over": ["LOOK_INSPECT"],
  "stare over": ["LOOK_INSPECT"],
  "observe target": ["LOOK_INSPECT"],
  "examine target": ["LOOK_INSPECT"],
  "inspect target": ["LOOK_INSPECT"],
  "look at target": ["LOOK_INSPECT"],
  "read page": ["LOOK_INSPECT"],
  "read diary": ["LOOK_INSPECT"],
  "read scroll": ["LOOK_INSPECT"],
  "read map": ["LOOK_INSPECT"],
  "read journal": ["LOOK_INSPECT"],
  "read note": ["LOOK_INSPECT"],
  "peer inside": ["LOOK_INSPECT"],
  "investigate room": ["LOOK_INSPECT"],
  "investigate area": ["LOOK_INSPECT"],
  "search room": ["LOOK_INSPECT"],
  "search area": ["LOOK_INSPECT"],
  "scan room": ["LOOK_INSPECT"],
  "scan area": ["LOOK_INSPECT"],
  stash: ["TAKE"],
  "stash item": ["TAKE"],
  "stash the": ["TAKE"],
  "stash target": ["TAKE"],
  appropriate: ["TAKE"],
  obtain: ["TAKE"],
  procure: ["TAKE"],
  "snatch up": ["TAKE"],
  "grab up": ["TAKE"],
  "put in pack": ["TAKE"],
  "put in backpack": ["TAKE"],
  "put into pocket": ["TAKE"],
  "put into bag": ["TAKE"],
  "put into pack": ["TAKE"],
  "put into backpack": ["TAKE"],
  "add item to inventory": ["TAKE"],
  "add target to inventory": ["TAKE"],
  rid: ["DROP"],
  "get rid of": ["DROP"],
  "get rid of the": ["DROP"],
  junk: ["DROP"],
  scrap: ["DROP"],
  unload: ["DROP"],
  "shut tight": ["CLOSE"],
  "lock tight": ["CLOSE"],
  "seal close": ["CLOSE"],
  "seal shut": ["CLOSE"],
  "unlock door with key": ["UNLOCK", "USE"],
  "unlock chest with key": ["UNLOCK", "USE"],
  "unlock gate with key": ["UNLOCK", "USE"],
  "unlock with key": ["UNLOCK", "USE"],
  "fiddle with": ["USE"],
  "play around with": ["USE"],
  ingest: ["USE"],
  imbibe: ["USE"],
  "extinguish flame": ["USE"],
  bestow: ["GIVE"],
  grant: ["GIVE"],
  provide: ["GIVE"],
  furnish: ["GIVE"],
  knapsack: ["INVENTORY"],
  sack: ["INVENTORY"],
  pouch: ["INVENTORY"],
  assail: ["FIGHT"],
  assault: ["FIGHT"],
  "cast magic": ["CAST"],
  "channel magic": ["CAST"],

  // Rich Synonym Expansion (AF-25 / Q4 Playtester feedback)
  clamber: ["MOVE", "USE"],
  plod: ["MOVE"],
  trek: ["MOVE"],
  drift: ["MOVE"],
  navigate: ["MOVE"],
  roam: ["MOVE"],
  meander: ["MOVE"],
  skulk: ["MOVE"],
  tiptoe: ["MOVE"],
  slither: ["MOVE"],
  shuffle: ["MOVE"],
  "dash to": ["MOVE"],
  "scamper to": ["MOVE"],
  "hurry to": ["MOVE"],
  "scurry to": ["MOVE"],
  audit: ["LOOK_INSPECT"],
  analyze: ["LOOK_INSPECT"],
  review: ["LOOK_INSPECT"],
  assess: ["LOOK_INSPECT"],
  gawk: ["LOOK_INSPECT"],
  pore: ["LOOK_INSPECT"],
  "pore over": ["LOOK_INSPECT"],
  "scan through": ["LOOK_INSPECT"],
  clutch: ["TAKE"],
  reclaim: ["TAKE"],
  intercept: ["TAKE"],
  swipe: ["TAKE"],
  filch: ["TAKE"],
  purloin: ["TAKE"],
  commandeer: ["TAKE"],
  "pocket item": ["TAKE"],
  "pocket target": ["TAKE"],
  relinquish: ["DROP"],
  forfeit: ["DROP"],
  dispose: ["DROP"],
  "cast aside": ["DROP"],
  "jettison item": ["DROP"],
  "unload item": ["DROP"],
  unveil: ["OPEN"],
  "unlock and open": ["OPEN"],
  slam: ["CLOSE"],
  block: ["CLOSE"],
  obstruct: ["CLOSE"],
  bar: ["CLOSE"],
  decrypt: ["UNLOCK", "USE"],
  "key unlock": ["UNLOCK", "USE"],
  "pick lock of": ["UNLOCK", "USE"],
  "disengage lock": ["UNLOCK", "USE"],
  quaff: ["USE"],
  swill: ["USE"],
  chew: ["USE"],
  "snuff out": ["USE"],
  "say to": ["TALK", "ASK"],
  "chatter with": ["TALK", "ASK"],
  petition: ["ASK"],
  duel: ["FIGHT"],
  clash: ["FIGHT"],
  pummel: ["FIGHT"],
  "clash with": ["FIGHT"],
  "strike at": ["FIGHT"],
  conjure: ["CAST"],
  "invoke magic": ["CAST"],
  "invoke spell": ["CAST"],
  "conjure spell": ["CAST"],
  "conjure magic": ["CAST"],
  fly: ["FLEE"],
  evade: ["FLEE"],
  avoid: ["FLEE"],
  "scurry away": ["FLEE"],
  "scamper away": ["FLEE"],
  "back away": ["FLEE"],
  "back off": ["FLEE"],
  "add object to inventory": ["TAKE"],

  // New Drop Verb Synonyms
  "get rid of item": ["DROP"],
  "get rid of target": ["DROP"],
  "get rid of object": ["DROP"],
  "dispose of item": ["DROP"],
  "dispose of target": ["DROP"],
  "dispose of object": ["DROP"],
  "drop item": ["DROP"],
  "drop target": ["DROP"],
  "drop object": ["DROP"],
  "discard target": ["DROP"],
  "discard object": ["DROP"],
  "throw item": ["DROP"],
  "throw target": ["DROP"],
  "throw object": ["DROP"],
  "toss item": ["DROP"],
  "toss target": ["DROP"],
  "toss object": ["DROP"],
  "dump item": ["DROP"],
  "dump target": ["DROP"],
  "dump object": ["DROP"],
  "toss aside": ["DROP"],
  "throw aside": ["DROP"],

  // New Open/Close Verb Synonyms
  "shut close the": ["CLOSE"],
  "close up the": ["CLOSE"],
  "shut tight the": ["CLOSE"],
  "lock tight the": ["CLOSE"],
  "seal close the": ["CLOSE"],
  "seal shut the": ["CLOSE"],
  "unseal door": ["OPEN"],
  "unlatch gate": ["OPEN"],
  "shut close item": ["CLOSE"],
  "shut close target": ["CLOSE"],
  "shut close object": ["CLOSE"],
  "close up item": ["CLOSE"],
  "close up target": ["CLOSE"],
  "close up object": ["CLOSE"],
  "shut up item": ["CLOSE"],
  "shut up target": ["CLOSE"],
  "shut up object": ["CLOSE"],
  "slam shut": ["CLOSE"],
  "slam shut item": ["CLOSE"],
  "slam shut target": ["CLOSE"],
  "slam shut object": ["CLOSE"],
  "unseal item": ["OPEN"],
  "unseal target": ["OPEN"],
  "unseal object": ["OPEN"],
  "unlatch item": ["OPEN"],
  "unlatch target": ["OPEN"],
  "unlatch object": ["OPEN"],
  "crack open item": ["OPEN"],
  "crack open target": ["OPEN"],
  "crack open object": ["OPEN"],
  "pry open item": ["OPEN"],
  "pry open target": ["OPEN"],
  "pry open object": ["OPEN"],
  "force open item": ["OPEN"],
  "force open target": ["OPEN"],
  "force open object": ["OPEN"],
  "pop open item": ["OPEN"],
  "pop open target": ["OPEN"],
  "pop open object": ["OPEN"],
  "remove lid of": ["OPEN"],
  "remove lid": ["OPEN"],

  // New Unlock Verb Synonyms
  "pick the lock of": ["UNLOCK", "USE"],
  "pick the lock on": ["UNLOCK", "USE"],
  "crack lock": ["UNLOCK", "USE"],
  "break lock": ["UNLOCK", "USE"],
  "bypass lock of": ["UNLOCK", "USE"],
  "deactivate security": ["UNLOCK", "USE"],
  "unlock gate": ["UNLOCK", "USE"],

  // New Use Verb Synonyms
  "manipulate lever": ["USE"],
  "pull trigger": ["USE"],
  "press button": ["USE"],
  "slide panel": ["USE"],
  "drink elixir": ["USE"],
  "drink potion": ["USE"],
  "consume potion": ["USE"],
  "wear armor": ["USE"],
  "wear ring": ["USE"],
  "equip sword": ["USE"],
  "wield sword": ["USE"],
  "wield weapon": ["USE"],
  "equip shield": ["USE"],

  // New Dialogue Verb Synonyms
  "converse with npc": ["TALK", "ASK"],
  "chat with npc": ["TALK", "ASK"],
  "greet merchant": ["TALK", "ASK"],
  "talk to shopkeeper": ["TALK", "ASK"],
  "speak to enforcer": ["TALK", "ASK"],
  "consult advisor": ["TALK", "ASK"],
  "ask boss about": ["ASK"],
  "ask capo about": ["ASK"],

  // New Give Verb Synonyms
  "hand over gold": ["GIVE"],
  "transfer funds": ["GIVE"],
  "pay merchant": ["GIVE"],
  "hand key to": ["GIVE"],
  "hand item": ["GIVE"],

  // New Fight Verb Synonyms
  "strike down enemy": ["FIGHT"],
  "defeat bandit": ["FIGHT"],
  "assail monster": ["FIGHT"],
  "bash gate": ["FIGHT", "USE"],
  "shatter lock": ["FIGHT", "USE"],
  "destroy barrier": ["FIGHT", "USE"],

  // Restored BUY/SELL verb category mappings
  "pay for": ["BUY"],
  "acquire from merchant": ["BUY"],
  "buy from merchant": ["BUY"],
  "purchase from merchant": ["BUY"],
  "procure from merchant": ["BUY"],
  vend: ["SELL"],
  hawk: ["SELL"],
  "dispose to merchant": ["SELL"],
  "sell to merchant": ["SELL"],
  "trade to merchant": ["SELL"],
  // Cycle #58 Parser Synonym Expansion
  "take from": ["TAKE"],
  "retrieve from": ["TAKE"],
  "extract from": ["TAKE"],
  "obtain from": ["TAKE"],
  "grab from": ["TAKE"],
  "steal from": ["TAKE"],
  "plunder from": ["TAKE"],
  "loot from": ["TAKE"],
  "snatch from": ["TAKE"],
  "gather from": ["TAKE"],
  "collect from": ["TAKE"],
  "remove from": ["TAKE"],
  "wield weapon on": ["USE"],
  "equip weapon on": ["USE"],
  "attack with": ["FIGHT"],
  "cast spell at": ["CAST"],
  "channel magic at": ["CAST"],
  "use magic at": ["CAST"],
  "shoot at": ["FIGHT"],
  "fire at": ["FIGHT"],
  "climb onto": ["MOVE", "USE"],
  "scramble to": ["MOVE"],
  "clamber to": ["MOVE"],
  "clamber up": ["MOVE"],
  "clamber down": ["MOVE"],
  "tiptoe to": ["MOVE"],
  "sneak to": ["MOVE"],
  "skulk to": ["MOVE"],
  "slither to": ["MOVE"],
  "shuffle to": ["MOVE"],
  "plod to": ["MOVE"],
  "trek to": ["MOVE"],
  "drift to": ["MOVE"],
  "navigate to": ["MOVE"],
  "roam to": ["MOVE"],
  "meander to": ["MOVE"],
  "fly from": ["FLEE"],

  // Cycle #59 Parser Synonym Expansion
  "head towards the": ["MOVE"],
  "walk towards the": ["MOVE"],
  "run towards the": ["MOVE"],
  "make way to": ["MOVE"],
  "make way towards": ["MOVE"],
  "move towards the": ["MOVE"],
  "travel towards": ["MOVE"],
  "navigate towards": ["MOVE"],
  "wander towards": ["MOVE"],
  "stroll towards": ["MOVE"],
  "march towards": ["MOVE"],
  "hike towards": ["MOVE"],
  "peer inside the": ["LOOK_INSPECT"],
  "look inside the": ["LOOK_INSPECT"],
  "look in the": ["LOOK_INSPECT"],
  "inspect closely the": ["LOOK_INSPECT"],
  "examine closely the": ["LOOK_INSPECT"],
  "search through": ["LOOK_INSPECT"],
  "rummage through": ["LOOK_INSPECT", "TAKE"],
  "scavenge through": ["LOOK_INSPECT", "TAKE"],
  "gaze upon the": ["LOOK_INSPECT"],
  "stare upon the": ["LOOK_INSPECT"],
  "read the book": ["LOOK_INSPECT"],
  "read the paper": ["LOOK_INSPECT"],
  "read the scroll": ["LOOK_INSPECT"],
  "read the note": ["LOOK_INSPECT"],
  "read the diary": ["LOOK_INSPECT"],
  "read the ledger": ["LOOK_INSPECT"],
  "read the manuscript": ["LOOK_INSPECT"],
  "read the tome": ["LOOK_INSPECT"],
  "pick the": ["TAKE"],
  "get the": ["TAKE"],
  "pocket the": ["TAKE"],
  "steal the": ["TAKE"],
  "appropriate the": ["TAKE"],
  "obtain the": ["TAKE"],
  "procure the": ["TAKE"],
  "snatch up the": ["TAKE"],
  "grab up the": ["TAKE"],
  "dispose of the": ["DROP"],
  "junk the": ["DROP"],
  "scrap the": ["DROP"],
  "unload the": ["DROP"],
  "relinquish the": ["DROP"],
  "forfeit the": ["DROP"],
  "discard the": ["DROP"],
  "throw the": ["DROP"],
  "place the": ["DROP"],
  "put down the": ["DROP"],
  "open the": ["OPEN"],
  "crack open the": ["OPEN"],
  "pry open the": ["OPEN"],
  "swing open the": ["OPEN"],
  "force open the": ["OPEN"],
  "pop open the": ["OPEN"],
  "unseal the": ["OPEN"],
  "unlatch the": ["OPEN"],
  "close the": ["CLOSE"],
  "shut the": ["CLOSE"],
  "slam the": ["CLOSE"],
  "seal the": ["CLOSE"],
  "lock the": ["CLOSE"],
  "shut up the": ["CLOSE"],
  "slam shut the": ["CLOSE"],
  "block the": ["CLOSE"],
  "bar the": ["CLOSE"],
  "unbolt the": ["UNLOCK", "USE"],
  "unfasten the": ["UNLOCK", "USE"],
  "release the": ["UNLOCK", "USE"],
  "disengage the": ["UNLOCK", "USE"],
  "unshackle the": ["UNLOCK", "USE"],
  "decrypt the": ["UNLOCK", "USE"],
  "activate the": ["USE"],
  "trigger the": ["USE"],
  "operate the": ["USE"],
  "manipulate the": ["USE"],
  "employ the": ["USE"],
  "utilize the": ["USE"],
  "consume the": ["USE"],
  "drink the": ["USE"],
  "eat the": ["USE"],
  "equip the": ["USE"],
  "wield the": ["USE"],
  "chat with the": ["TALK", "ASK"],
  "converse with the": ["TALK", "ASK"],
  "question the": ["TALK", "ASK"],
  "discuss with the": ["TALK", "ASK"],
  "ask the about": ["ASK"],
  "inquire with": ["TALK", "ASK"],
  "inquire with the": ["TALK", "ASK"],
  "give the to": ["GIVE", "ASK"],
  "hand the to": ["GIVE", "ASK"],
  "deliver the to": ["GIVE"],
  "present the to": ["GIVE"],
  "submit the to": ["GIVE"],
  "offer the to": ["GIVE"],
  "pay the": ["GIVE"],
  "trade the to": ["GIVE"],
  "hit the": ["FIGHT"],
  "battle the": ["FIGHT"],
  "slash the": ["FIGHT"],
  "punch the": ["FIGHT"],
  "kick the": ["FIGHT"],
  "shoot the": ["FIGHT"],
  "fire at the": ["FIGHT"],
  "engage the": ["FIGHT"],
  "smash the": ["USE", "FIGHT"],
  "beat the": ["FIGHT"],
  "bash the": ["FIGHT"],
  "stab the": ["FIGHT"],
  "confront the": ["FIGHT"],
  "assail the": ["FIGHT"],
  "assault the": ["FIGHT"],
  "duel the": ["FIGHT"],
  "clash with the": ["FIGHT"],
  "cast spell on the": ["CAST"],
  "channel spell on the": ["CAST"],
  "use magic on the": ["CAST"],
  "cast magic on the": ["CAST"],
  "cast fireball on the": ["CAST"],
  "cast heal on the": ["CAST"],
  "cast freeze on the": ["CAST"],
  "cast lightning on the": ["CAST"],
  "cast poison on the": ["CAST"],
  "run away from the": ["FLEE"],
  "escape from the": ["FLEE"],
  "retreat from the": ["FLEE"],
  "withdraw from the": ["FLEE"],
  "flee from the": ["FLEE"],
  "scurry away from the": ["FLEE"],
  "scamper away from the": ["FLEE"],
  "buy the from": ["BUY"],
  "purchase the from": ["BUY"],
  "buy from the": ["BUY"],
  "purchase from the": ["BUY"],
  "sell the to": ["SELL"],
  "sell to the": ["SELL"],
  "trade the to the": ["SELL"],

  // Cycle #26 / Phase 12 Synonym Expansion
  "vault to": ["MOVE"],
  "skitter to": ["MOVE"],
  "scud to": ["MOVE"],
  "flit to": ["MOVE"],
  "wend one's way to": ["MOVE"],
  "wend ones way to": ["MOVE"],
  vault: ["MOVE"],
  skitter: ["MOVE"],
  scud: ["MOVE"],
  flit: ["MOVE"],
  wend: ["MOVE"],
  contemplate: ["LOOK_INSPECT"],
  "inspect the contents of": ["LOOK_INSPECT"],
  "look through the contents of": ["LOOK_INSPECT"],
  "cart off": ["TAKE"],
  pluck: ["TAKE"],
  "lay hands on": ["TAKE"],
  "cart off the": ["TAKE"],
  "pluck the": ["TAKE"],
  "throw down": ["DROP"],
  "throw down the": ["DROP"],
  "block up": ["CLOSE"],
  "block up the": ["CLOSE"],
  "crack lock on": ["UNLOCK", "USE"],
  "disengage lock on": ["UNLOCK", "USE"],
  "undo the lock on": ["UNLOCK", "USE"],
  "gulp down the": ["USE"],
  "gulp down": ["USE"],
  "don the": ["USE"],
  "lay into": ["FIGHT"],
  "lay into the": ["FIGHT"],
  "deal blow to": ["FIGHT"],
  "deal blow to the": ["FIGHT"],
  "exchange words with": ["TALK", "ASK"],
  "exchange words with the": ["TALK", "ASK"],
  "hold conversation with": ["TALK", "ASK"],
  "hold conversation with the": ["TALK", "ASK"],
};

// Map engine action type to canonical categories to check verb matches.
function getActionCategory(type: string): string {
  const t = type.toUpperCase();
  if (t === "MOVE" || t === "GO") return "MOVE";
  if (t === "LOOK" || t === "INSPECT" || t === "READ") return "LOOK_INSPECT";
  if (t === "TAKE") return "TAKE";
  if (t === "DROP") return "DROP";
  if (t === "OPEN") return "OPEN";
  if (t === "CLOSE") return "CLOSE";
  if (t === "UNLOCK") return "UNLOCK";
  if (t === "USE" || t === "CRAFT") return "USE";
  if (t === "TALK") return "TALK";
  if (t === "ASK") return "ASK";
  if (t === "GIVE") return "GIVE";
  if (t === "INVENTORY") return "INVENTORY";
  if (t === "FIGHT") return "FIGHT";
  if (t === "CAST") return "CAST";
  if (t === "FLEE") return "FLEE";
  if (t === "BUY") return "BUY";
  if (t === "SELL") return "SELL";
  return t;
}

/**
 * Controlled command parser matches a human text command against the set of
 * currently legal available actions.
 *
 * Exposes a classic adventure game interface backed by absolute determinism.
 */
const compoundVerbs = [
  // Rich Synonym Expansion (AF-25 / Q4 Playtester feedback)
  "acquire from merchant",
  "buy from merchant",
  "purchase from merchant",
  "procure from merchant",
  "dispose to merchant",
  "sell to merchant",
  "trade to merchant",
  "invoke magic",
  "invoke spell",
  "conjure spell",
  "conjure magic",
  "cast fireball on",
  "cast fireball",
  "cast heal on",
  "cast heal",
  "cast freeze on",
  "cast freeze",
  "cast lightning on",
  "cast lightning",
  "cast poison on",
  "cast poison",
  "scurry away",
  "scamper away",
  "back away",
  "back off",
  "pocket item",
  "pocket target",
  "dispose of",
  "cast aside",
  "jettison item",
  "unload item",
  "unlock and open",
  "key unlock",
  "pick lock of",
  "scan through",
  "pay for",

  // Task-F24 New long compound verbs
  "add target to inventory",
  "add item to inventory",
  "unlock chest with key",
  "unlock door with key",
  "unlock gate with key",
  "put into backpack",
  "get rid of the",
  "put into pocket",
  "put into bag",
  "put into pack",
  "put in backpack",
  "observe target",
  "examine target",
  "inspect target",
  "look at target",
  "read scroll",
  "read journal",
  "read diary",
  "read page",
  "investigate room",
  "investigate area",
  "search room",
  "search area",
  "scan room",
  "scan area",
  "close up the",
  "shut tight the",
  "lock tight the",
  "seal close the",
  "seal shut the",
  "unlock with key",
  "get rid of",
  "play around with",
  "extinguish flame",
  "ask npc about",
  "ask npc for",
  "inquire about",
  "stash target",
  "stash item",
  "close up",
  "shut tight",
  "lock tight",
  "seal close",
  "seal shut",
  "go northward",
  "go southward",
  "go eastward",
  "go westward",
  "walk northward",
  "walk southward",
  "walk eastward",
  "walk westward",
  "run northward",
  "run southward",
  "run eastward",
  "run westward",
  "head northward",
  "head southward",
  "head eastward",
  "head westward",

  // 3-word or more phrasal verbs/prepositional phrases
  "engage in combat with the",
  "engage in battle with the",
  "look closely at the",
  "look inside of the",
  "peer down into the",
  "interact with the",
  "speak with the",
  "climb down the",
  "peer into the",
  "talk with the",
  "speak to the",
  "scale up the",
  "climb up the",
  "climb on the",
  "retrieve the",
  "strike down",
  "engage with",
  "look at the",
  "look in the",
  "pick up the",
  "collect the",
  "walk to the",
  "head to the",
  "move to the",
  "go down the",
  "talk to the",
  "run to the",
  "attack the",
  "strike the",
  "unlock the",
  "snatch the",
  "go to the",
  "go up the",
  "press the",
  "beat down",
  "take the",
  "grab the",
  "pull the",
  "push the",
  "flip the",
  "turn the",
  "kill the",
  "slay the",
  "use the",
  "ask the",
  "engage in combat with",
  "engage in battle with",
  "engage combat with",
  "engage battle with",
  "request access to",
  "inspect closely",
  "look closely at",
  "examine closely",
  "descend down to",
  "squeeze through",
  "peer inside of",
  "look inside of",
  "take a look at",
  "peer down into",
  "look down into",
  "bribe npc with",
  "negotiate with",
  "inquire about",
  "run away from",
  "climb down to",
  "crawl through",
  "withdraw from",
  "purchase from",
  "converse with",
  "acquire from",
  "climb through",
  "grab hold of",
  "pass through",
  "walk through",
  "step through",
  "retreat from",
  "peer into of",
  "look through",
  "leave behind",
  "discuss with",
  "take hold of",
  "descend down",
  "descend into",
  "walk towards",
  "head towards",
  "slip through",
  "consult with",
  "climb up to",
  "scramble up",
  "unlock with",
  "escape from",
  "glance upon",
  "look inside",
  "query about",
  "parley with",
  "run towards",
  "inquire for",
  "swing open",
  "shut close",
  "slash with",
  "fight with",
  "stare upon",
  "peer at of",
  "look in to",
  "climb down",
  "go outside",
  "head north",
  "head south",
  "look under",
  "throw away",
  "crack open",
  "speak with",
  "trade with",
  "place down",
  "look up at",
  "present to",
  "deliver to",
  "force open",
  "go towards",
  "go back to",
  "fling away",
  "drink from",
  "gaze upon",
  "gather up",
  "climb up",
  "climb on",
  "scale up",
  "go inside",
  "head east",
  "head west",
  "head down",
  "ask about",
  "report on",
  "check out",
  "gaze at",
  "glance at",
  "stare at",
  "peer into",
  "put down",
  "drop off",
  "pry open",
  "chat with",
  "talk with",
  "hand over",
  "trade for",
  "give to",
  "hand to",
  "buy from",
  "sell to",
  "go down",
  "flee from",
  "peer down",
  "look down",
  "gaze down",
  "set down",
  "lay down",
  "pop open",
  "offer to",
  "toss away",
  "cast away",
  "agree to",
  "peer at",
  "look in",
  "speak to",
  "run away",
  "hit with",
  "shout to",
  "cast off",
  "climb to",
  "hoist up",
  "take up",
  "open up",
  "shut up",
  "head up",
  "look at",
  "pick up",
  "talk to",
  "turn in",
  "ask for",
  "walk to",
  "move to",
  "go back",
  "yell to",
  "call to",
  "look up",
  "gaze up",
  "run to",
  "eat up",
  "go to",
  "go up",

  // Cycle #58 Parser Compound Verbs
  "strike with",
  "hit with",
  "attack with",
  "take from",
  "retrieve from",
  "extract from",
  "obtain from",
  "grab from",
  "steal from",
  "plunder from",
  "loot from",
  "snatch from",
  "gather from",
  "collect from",
  "remove from",
  "cast spell at",
  "channel magic at",
  "use magic at",
  "shoot at",
  "fire at",

  // --- Parser Category Overrides (Phases mapping specific combinations to non-default categories) ---
  // Inventory checking verbs mapped to INVENTORY category
  "check inventory",
  "show inventory",
  "view inventory",
  "list inventory",
  "check backpack",
  "check pack",
  "check bag",
  "check bags",
  "check pockets",
  "show items",
  "check items",
  "list items",
  "view items",
  "my items",
  "view bag",
  "view pack",
  "backpack",

  // Spellcasting verbs mapping to CAST category
  "use magic on",
  "use magic",
  "cast spell on",
  "cast spell",
  "cast magic on",
  "channel spell on",
  "channel magic on",

  // Key usage mapping to UNLOCK category
  "use key to unlock",
  "use key to open",

  // Newly Added Compound Verbs (AF-27 / Q4 Synonym Expansion)
  "bounce to",
  "spring to",
  "dive to",
  "plunge to",
  "slip to",
  "wander to",
  "stroll to",
  "march to",
  "jog to",
  "hike to",
  "sprint to",
  "hasten to",
  "slip in",
  "slip into",
  "slip out",
  "slip out of",
  "climb into",
  "crawl into",
  "squeeze into",
  "scramble into",
  "clamber into",
  "pass into",
  "plunge into",
  "dive into",
  "jump into",
  "leap into",
  "hop into",
  "bound into",
  "scurry into",
  "scamper into",
  "rush into",
  "charge into",
  "back into",
  "back to",
  "walk into",
  "go into",
  "run into",
  "step into",
  "advance to",
  "proceed to",
  "travel to",
  "journey to",
  "head to",
  "move to",
  "go to",
  "walk to",
  "run to",
  "step to",
  "jog to",
  "hop to",
  "leap to",
  "jump to",
  "bound to",
  "scramble to",
  "clamber to",
  "climb to",
  "scale to",
  "ascend to",
  "descend to",
  "gawk at",
  "gaze over",
  "stare over",
  "glance over",
  "read page",
  "read book",
  "read diary",
  "read scroll",
  "read map",
  "read journal",
  "read note",
  "read sign",
  "read letter",
  "read text",
  "read writing",
  "read inscription",
  "read notes",
  "read paper",
  "peer inside",
  "peer in",
  "peer through",
  "peer down",
  "peer up",
  "peer at",
  "look through",
  "look under",
  "look inside",
  "look in",
  "look down",
  "look up",
  "gaze down",
  "gaze up",
  "gaze inside",
  "stare inside",
  "check on",
  "check target",
  "check out",
  "check item",
  "check room",
  "check area",
  "check surroundings",
  "examine target",
  "examine item",
  "examine room",
  "examine area",
  "examine object",
  "examine surroundings",
  "inspect target",
  "inspect item",
  "inspect room",
  "inspect area",
  "inspect object",
  "inspect surroundings",
  "study target",
  "study item",
  "study room",
  "study area",
  "study object",
  "study surroundings",
  "scrutinize target",
  "scrutinize item",
  "scrutinize room",
  "scrutinize area",
  "scrutinize object",
  "scrutinize surroundings",
  "view target",
  "view item",
  "view room",
  "view area",
  "view object",
  "view surroundings",
  "observe target",
  "observe item",
  "observe room",
  "observe area",
  "observe object",
  "observe surroundings",
  "scan target",
  "scan item",
  "scan room",
  "scan area",
  "scan object",
  "scan surroundings",
  "search target",
  "search item",
  "search room",
  "search area",
  "search object",
  "search surroundings",
  "grab target",
  "grab item",
  "grab object",
  "grab hold of",
  "take target",
  "take item",
  "take object",
  "take hold of",
  "get target",
  "get item",
  "get object",
  "get hold of",
  "retrieve target",
  "retrieve item",
  "retrieve object",
  "collect target",
  "collect item",
  "collect object",
  "pick up target",
  "pick up item",
  "pick up object",
  "stash target",
  "stash item",
  "stash object",
  "pocket target",
  "pocket item",
  "pocket object",
  "put in pocket",
  "put in bag",
  "put in pack",
  "put in backpack",
  "put into pocket",
  "put into bag",
  "put into pack",
  "put into backpack",
  "add to inventory",
  "add item to inventory",
  "add target to inventory",
  "add object to inventory",
  "gather up",
  "scoop up",
  "take up",
  "lift up",
  "hoist up",
  "snatch up",
  "grab up",
  "get rid of item",
  "get rid of target",
  "get rid of object",
  "dispose of item",
  "dispose of target",
  "dispose of object",
  "drop item",
  "drop target",
  "drop object",
  "discard target",
  "discard object",
  "throw item",
  "throw target",
  "throw object",
  "toss item",
  "toss target",
  "toss object",
  "dump item",
  "dump target",
  "dump object",
  "toss aside",
  "throw aside",
  "shut close the",
  "close up the",
  "shut tight the",
  "lock tight the",
  "seal close the",
  "seal shut the",
  "unseal door",
  "unlatch gate",
  "shut close item",
  "shut close target",
  "shut close object",
  "close up item",
  "close up target",
  "close up object",
  "shut up item",
  "shut up target",
  "shut up object",
  "shut tight",
  "lock tight",
  "seal close",
  "seal shut",
  "shut lid of",
  "shut lid",
  "close lid of",
  "close lid",
  "slam shut",
  "slam shut item",
  "slam shut target",
  "slam shut object",
  "unseal item",
  "unseal target",
  "unseal object",
  "unlatch item",
  "unlatch target",
  "unlatch object",
  "crack open item",
  "crack open target",
  "crack open object",
  "pry open item",
  "pry open target",
  "pry open object",
  "force open item",
  "force open target",
  "force open object",
  "pop open item",
  "pop open target",
  "pop open object",
  "open lid of",
  "open lid",
  "slide lid of",
  "slide lid",
  "lift lid of",
  "lift lid",
  "remove lid of",
  "remove lid",
  "unlock door with key",
  "unlock chest with key",
  "unlock gate with key",
  "unlock with key",
  "pick the lock of",
  "pick the lock on",
  "crack lock",
  "break lock",
  "bypass lock of",
  "deactivate security",
  "fiddle with",
  "play around with",
  "extinguish flame",
  "manipulate lever",
  "pull trigger",
  "press button",
  "slide panel",
  "drink elixir",
  "drink potion",
  "consume potion",
  "wear armor",
  "wear ring",
  "equip sword",
  "wield sword",
  "wield weapon",
  "equip shield",
  "use item on",
  "use item with",
  "use the",
  "pull the",
  "push the",
  "press the",
  "flip the",
  "turn the",
  "interact with the",
  "activate mechanism",
  "pull lever",
  "push button",
  "flip switch",
  "turn valve",
  "strike match",
  "light torch",
  "light up",
  "light",
  "disarm",
  "defuse",
  "disable",
  "disarm trap on",
  "disarm trap",
  "disable trap on",
  "disable trap",
  "deactivate trap on",
  "deactivate trap",
  "fasten",
  "bind",
  "tie rope to",
  "attach rope to",
  "fasten rope to",
  "interact with",
  "drink from",
  "sip from",
  "eat up",
  "converse with npc",
  "chat with npc",
  "greet merchant",
  "talk to shopkeeper",
  "speak to enforcer",
  "consult advisor",
  "ask boss about",
  "ask capo about",
  "hand over gold",
  "transfer funds",
  "pay merchant",
  "hand key to",
  "hand item",
  "strike down enemy",
  "defeat bandit",
  "assail monster",
  "bash gate",
  "shatter lock",
  "destroy barrier",

  // Cycle #26 / Phase 12 Compound Verbs
  "vault to",
  "skitter to",
  "scud to",
  "flit to",
  "wend one's way to",
  "wend ones way to",
  "inspect the contents of",
  "look through the contents of",
  "cart off",
  "lay hands on",
  "cart off the",
  "pluck the",
  "throw down",
  "throw down the",
  "unload the",
  "block up",
  "block up the",
  "crack lock on",
  "disengage lock on",
  "undo the lock on",
  "gulp down the",
  "gulp down",
  "don the",
  "lay into",
  "lay into the",
  "deal blow to",
  "deal blow to the",
  "exchange words with",
  "exchange words with the",
  "hold conversation with",
  "hold conversation with the",
].sort((a, b) => b.length - a.length);

function levenshtein(a: string, b: string): number {
  const tmp: number[][] = [];
  for (let i = 0; i <= a.length; i++) {
    tmp[i] = [i];
  }
  for (let j = 0; j <= b.length; j++) {
    tmp[0][j] = j;
  }
  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      tmp[i][j] = Math.min(
        tmp[i - 1][j] + 1, // deletion
        tmp[i][j - 1] + 1, // insertion
        tmp[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1) // substitution
      );
    }
  }
  return tmp[a.length][b.length];
}

function isSameAction(act1: Action, act2: Action): boolean {
  if (act1.type !== act2.type) return false;
  const keys1 = Object.keys(act1) as (keyof Action)[];
  const keys2 = Object.keys(act2) as (keyof Action)[];
  if (keys1.length !== keys2.length) return false;
  for (const k of keys1) {
    if ((act1 as any)[k] !== (act2 as any)[k]) return false;
  }
  return true;
}

const SYNONYM_GROUPS = [
  [
    "contract",
    "contracts",
    "mission",
    "missions",
    "quest",
    "quests",
    "job",
    "jobs",
    "task",
    "tasks",
    "assignment",
    "bounty",
    "work",
    "objective",
    "duty",
    "agreement",
    "deal",
  ],
  [
    "token",
    "tokens",
    "badge",
    "badges",
    "pass",
    "passes",
    "seal",
    "seals",
    "permit",
    "permits",
    "voucher",
    "ticket",
    "credential",
    "credentials",
    "diploma",
    "license",
    "warrant",
    "visa",
  ],
  [
    "smuggler",
    "smugglers",
    "capo",
    "boss",
    "leader",
    "chief",
    "head",
    "commander",
    "officer",
    "captain",
    "underboss",
    "don",
    "kingpin",
  ],
  [
    "sheriff",
    "enforcer",
    "enforcers",
    "warden",
    "wardens",
    "guard",
    "guards",
    "sentinel",
    "sentry",
    "patrol",
    "constable",
    "deputy",
    "peacekeeper",
    "soldier",
    "watchman",
    "watchmen",
    "garrison",
    "policeman",
    "officer",
  ],
  ["commander", "officer", "captain", "lieutenant", "general", "admiral", "chief", "leader", "major"],
  [
    "gold",
    "coins",
    "coin",
    "money",
    "wealth",
    "trust",
    "currency",
    "funds",
    "cash",
    "loot",
    "riches",
    "payment",
    "fee",
    "change",
    "silver",
    "copper",
    "mulla",
    "dough",
    "capital",
  ],
  [
    "cargo",
    "crate",
    "box",
    "package",
    "goods",
    "contraband",
    "merchandise",
    "freight",
    "load",
    "shipment",
    "consignment",
    "delivery",
    "pack",
    "bundle",
    "bale",
    "item",
    "object",
    "thing",
  ],
  [
    "gem",
    "stone",
    "jewel",
    "crystal",
    "gemstone",
    "diamond",
    "ruby",
    "emerald",
    "sapphire",
    "amethyst",
    "pearl",
    "opal",
    "garnet",
    "topaz",
    "jade",
    "turquoise",
    "onyx",
    "obsidian",
    "geode",
    "item",
    "object",
    "thing",
  ],
  [
    "trophy",
    "chalice",
    "cup",
    "award",
    "prize",
    "goblet",
    "relic",
    "memento",
    "souvenir",
    "token",
    "item",
    "object",
    "thing",
  ],
  [
    "treasure",
    "chest",
    "loot",
    "booty",
    "spoils",
    "hoard",
    "riches",
    "valuables",
    "windfall",
    "coffer",
    "item",
    "object",
    "thing",
  ],
  ["bye", "goodbye", "leave", "exit", "farewell", "adieu", "depart", "quit", "go", "withdraw"],
  [
    "key",
    "keys",
    "passkey",
    "lockpick",
    "pick",
    "skeleton_key",
    "latchkey",
    "opener",
    "device",
    "wrench",
    "lock-pick",
    "tool",
    "item",
    "object",
    "thing",
  ],
  [
    "chest",
    "box",
    "crate",
    "coffer",
    "sarcophagus",
    "safe",
    "trunk",
    "cabinet",
    "drawer",
    "receptacle",
    "locker",
    "vault",
    "casket",
    "container",
    "wardrobe",
    "cupboard",
    "closet",
    "urn",
    "jar",
    "vase",
    "lockbox",
    "strongbox",
    "bin",
    "item",
    "object",
    "thing",
  ],
  [
    "sword",
    "blade",
    "weapon",
    "arms",
    "iron_sword",
    "rapier",
    "dagger",
    "sabre",
    "scimitar",
    "broadsword",
    "knife",
    "dirk",
    "cutlass",
    "foil",
    "estoc",
    "falchion",
    "gladius",
    "claymore",
    "katana",
    "longsword",
    "shortsword",
    "epee",
    "stiletto",
    "brand",
    "steel",
    "item",
    "object",
    "thing",
  ],
  ["axe", "hatchet", "tomahawk", "battleaxe", "cleaver", "chopper", "weapon", "arms", "item", "object", "thing"],
  [
    "mace",
    "club",
    "flail",
    "hammer",
    "warhammer",
    "cudgel",
    "maul",
    "bludgeon",
    "baton",
    "staff",
    "weapon",
    "arms",
    "item",
    "object",
    "thing",
  ],
  [
    "spear",
    "halberd",
    "lance",
    "pike",
    "quarterstaff",
    "staff",
    "javelin",
    "harpoon",
    "trident",
    "weapon",
    "arms",
    "item",
    "object",
    "thing",
  ],
  ["bow", "crossbow", "shortbow", "longbow", "recurve", "weapon", "arms", "item", "object", "thing"],
  ["arrow", "bolt", "quiver", "projectile", "shaft", "missile", "ammo", "ammunition", "item", "object", "thing"],
  [
    "map",
    "book",
    "journal",
    "scroll",
    "sign",
    "inscription",
    "writing",
    "note",
    "letter",
    "page",
    "tome",
    "volume",
    "parchment",
    "document",
    "diary",
    "ledger",
    "manuscript",
    "pamphlet",
    "leaflet",
    "flyer",
    "tablet",
    "plaque",
    "codex",
    "atlas",
    "sheet",
    "slate",
    "parchments",
    "signboard",
    "recipe",
    "formula",
    "instructions",
    "schematic",
    "blueprint",
    "diagram",
    "pattern",
    "plan",
    "item",
    "object",
    "thing",
  ],
  [
    "door",
    "gate",
    "portal",
    "way",
    "passage",
    "passageway",
    "doorway",
    "hatch",
    "grate",
    "barrier",
    "entrance",
    "exit",
    "doorstep",
    "threshold",
    "opening",
    "portcullis",
    "grille",
    "window",
    "vent",
    "manhole",
    "trapdoor",
    "curtain",
    "arch",
    "archway",
    "shutter",
    "valance",
    "screen",
  ],
  [
    "torch",
    "light",
    "lantern",
    "candle",
    "match",
    "lamp",
    "flare",
    "beacon",
    "illumination",
    "firebrand",
    "glowstick",
    "flashlight",
    "tinderbox",
    "fire",
    "flame",
    "candelabra",
    "taper",
    "luminary",
    "item",
    "object",
    "thing",
  ],
  [
    "npc",
    "character",
    "merchant",
    "vendor",
    "trader",
    "dealer",
    "seller",
    "clerk",
    "shopkeeper",
    "person",
    "individual",
    "figure",
    "citizen",
    "townsperson",
    "commoner",
    "peasant",
    "villager",
    "wanderer",
    "stranger",
    "guide",
    "assistant",
    "guard",
    "guards",
    "sheriff",
    "enforcer",
    "enforcers",
    "commander",
    "officer",
    "captain",
    "advisor",
    "capo",
    "boss",
    "leader",
    "chief",
    "underboss",
    "warden",
    "wardens",
    "patrol",
    "sentinel",
    "sentry",
  ],
  [
    "guild",
    "faction",
    "syndicate",
    "cartel",
    "alliance",
    "cabal",
    "order",
    "society",
    "brotherhood",
    "league",
    "clan",
    "association",
    "federation",
    "union",
    "coalition",
    "outfit",
    "crew",
    "gang",
    "party",
    "sect",
    "cult",
    "organization",
    "club",
    "lodge",
  ],
  [
    "water",
    "drink",
    "liquid",
    "beverage",
    "potion",
    "elixir",
    "flask",
    "bottle",
    "brew",
    "draft",
    "tonic",
    "mead",
    "wine",
    "ale",
    "beer",
    "cider",
    "rum",
    "poison",
    "venom",
    "oil",
    "fluid",
    "phial",
    "vial",
    "potion_of_healing",
    "healing_potion",
    "draught",
    "mixture",
    "concoction",
    "infusion",
    "nectar",
    "serum",
    "item",
    "object",
    "thing",
  ],
  [
    "food",
    "ration",
    "bread",
    "meat",
    "herb",
    "berry",
    "ingredient",
    "meal",
    "provisions",
    "sustenance",
    "morsel",
    "snack",
    "apple",
    "fruit",
    "cheese",
    "stew",
    "soup",
    "jerky",
    "rations",
    "feast",
    "grub",
    "diet",
    "nourishment",
    "fodder",
    "item",
    "object",
    "thing",
  ],
  [
    "well",
    "pit",
    "hole",
    "shaft",
    "abyss",
    "crater",
    "chasm",
    "wellspring",
    "fountain",
    "geyser",
    "cistern",
    "basin",
    "cavity",
    "trench",
    "sinkhole",
    "opening",
    "vent",
    "excavation",
  ],
  [
    "rope",
    "coil",
    "line",
    "cord",
    "tether",
    "thread",
    "twine",
    "string",
    "lasso",
    "cable",
    "chain",
    "shackle",
    "binding",
    "strap",
    "wire",
    "tethering",
    "lashing",
    "item",
    "object",
    "thing",
  ],
  [
    "lever",
    "switch",
    "handle",
    "crank",
    "pull",
    "button",
    "trigger",
    "knob",
    "dial",
    "pedal",
    "valve",
    "keypad",
    "latch",
    "control",
    "toggle",
    "item",
    "object",
    "thing",
  ],
  [
    "ring",
    "band",
    "circlet",
    "jewelry",
    "signet",
    "loop",
    "earring",
    "bracelet",
    "bangle",
    "brooch",
    "pin",
    "clasp",
    "gemstone_ring",
    "item",
    "object",
    "thing",
  ],
  [
    "shield",
    "buckler",
    "aegis",
    "ward",
    "defense",
    "targe",
    "protector",
    "shielding",
    "bulwark",
    "heater",
    "kite_shield",
    "armor",
    "item",
    "object",
    "thing",
  ],
  [
    "goblin",
    "orc",
    "monster",
    "beast",
    "creature",
    "enemy",
    "foe",
    "adversary",
    "ghoul",
    "bandit",
    "thief",
    "rogue",
    "outlaw",
    "brigand",
    "raider",
    "skeleton",
    "zombie",
    "troll",
    "slime",
    "spider",
    "wolf",
    "bat",
    "dragon",
    "specter",
    "wraith",
    "fiend",
    "minion",
    "demon",
    "imp",
    "gargoyle",
    "golem",
    "phantom",
    "spectre",
    "opponent",
    "target",
    "ghost",
    "ghosts",
  ],
  [
    "altar",
    "shrine",
    "pedestal",
    "plinth",
    "platform",
    "dais",
    "lectern",
    "podium",
    "table",
    "slab",
    "bench",
    "desk",
    "hearth",
  ],
  [
    "crown",
    "coronet",
    "diadem",
    "tiara",
    "wreath",
    "circlet",
    "headpiece",
    "helmet",
    "helm",
    "cap",
    "item",
    "object",
    "thing",
  ],
  [
    "necklace",
    "amulet",
    "pendant",
    "talisman",
    "charm",
    "locket",
    "choker",
    "collar",
    "neckpiece",
    "item",
    "object",
    "thing",
  ],
  [
    "boots",
    "shoes",
    "footwear",
    "greaves",
    "sabaton",
    "sabtons",
    "sandals",
    "slippers",
    "boot",
    "shoe",
    "socks",
    "item",
    "object",
    "thing",
  ],
  [
    "cloak",
    "robe",
    "cape",
    "mantle",
    "cowl",
    "shawl",
    "tunic",
    "shroud",
    "poncho",
    "garment",
    "apparel",
    "attire",
    "vestment",
    "wrap",
    "item",
    "object",
    "thing",
  ],
  [
    "armor",
    "mail",
    "plate",
    "jerkin",
    "cuirass",
    "breastplate",
    "hauberk",
    "protection",
    "suit",
    "leather_armor",
    "chainmail",
    "scale_mail",
    "defense",
    "garment",
    "item",
    "object",
    "thing",
  ],
  [
    "ladder",
    "stairs",
    "steps",
    "staircase",
    "stairway",
    "rung",
    "rungs",
    "banister",
    "escalator",
    "climbway",
    "climb",
    "ascent",
  ],
  [
    "wall",
    "barrier",
    "rock",
    "cliff",
    "cliffside",
    "stone",
    "boulder",
    "rampart",
    "masonry",
    "brickwork",
    "palisade",
    "hedge",
    "fence",
    "dike",
    "embankment",
    "parapet",
  ],
  [
    "statue",
    "idol",
    "monument",
    "effigy",
    "gargoyle",
    "sculpture",
    "carving",
    "totem",
    "bust",
    "figurine",
    "sculpture",
    "monument",
    "item",
    "object",
    "thing",
  ],
  [
    "tool",
    "pliers",
    "wrench",
    "crowbar",
    "screwdriver",
    "chisel",
    "hammer",
    "saw",
    "drill",
    "mallet",
    "pickaxe",
    "spade",
    "shovel",
    "item",
    "object",
    "thing",
  ],
  ["backpack", "knapsack", "bag", "pouch", "sack", "satchel", "container", "pack", "item", "object", "thing"],
  ["ruins", "temple", "shrine", "chapel", "church", "monastery", "sanctuary", "cathedral", "crypt", "vault", "tomb"],
  ["forest", "woods", "grove", "jungle", "wilderness", "copse", "thicket", "brush"],
  ["clutter", "debris", "rubble", "wreckage", "detritus", "timbers", "junk", "litter", "remains"],
  ["tree", "shrub", "bush", "plant", "foliage", "undergrowth", "flora", "sapling", "log", "stump"],
  ["river", "stream", "creek", "brook", "flow", "waterway", "canal", "riverbed"],
  ["bridge", "crossing", "overpass", "span", "viaduct", "footbridge"],
  ["bed", "cot", "pallet", "hammock", "mattress", "couch", "sofa", "bunk"],
  ["shelf", "mantel", "rack", "stand", "ledge", "bracket"],
  ["mirror", "looking-glass", "glass", "reflector", "speculum"],
  ["hearth", "fireplace", "chimney", "stove", "grate", "firepit"],
  ["gloves", "gauntlets", "mittens", "bracers", "gloves", "mitts"],
  ["hat", "cap", "hood", "bonnet", "coif", "headwear"],
  ["belt", "girdle", "sash", "strap", "banderole"],
  [
    "strike",
    "hit",
    "attack",
    "fight",
    "assail",
    "slash",
    "thrust",
    "bash",
    "clout",
    "wallop",
    "pummel",
    "smash",
    "engage",
    "confront",
    "accost",
    "battle",
    "combat",
    "slay",
    "kill",
    "murder",
    "terminate",
    "defeat",
    "destroy",
  ],
  ["cast", "spell", "magic", "incantation", "hex", "curse", "charm", "enchantment", "conjure", "evoke", "summon"],
  // Cycle #58 Parser Noun & Concept Synonym Expansion
  [
    "fire",
    "flame",
    "flames",
    "heat",
    "blaze",
    "ember",
    "spark",
    "conflagration",
    "fireball",
    "combustion",
    "pyre",
    "inferno",
  ],
  ["ice", "frost", "cold", "chill", "glacier", "glacial", "snow", "blizzard", "freeze", "cryo"],
  ["lightning", "spark", "bolt", "electricity", "shock", "thunderbolt", "volt", "zap", "current", "charge", "voltage"],
  ["poison", "venom", "toxin", "acid", "blight", "corruption", "venomous", "slime", "sludge", "noxious"],
  [
    "potion",
    "elixir",
    "flask",
    "vial",
    "bottle",
    "phial",
    "drink",
    "tonic",
    "brew",
    "draught",
    "mixture",
    "concoction",
  ],
  ["scroll", "tome", "book", "journal", "diary", "page", "parchment", "document", "ledger", "manuscript", "codex"],
  ["lever", "switch", "handle", "crank", "pull", "button", "trigger", "knob", "dial", "pedal", "valve"],
  ["chest", "coffer", "safe", "vault", "strongbox", "lockbox", "box", "crate", "trunk", "casket", "sarcophagus"],
  ["key", "passkey", "skeleton_key", "lockpick", "pick", "latchkey", "keycard", "passcode", "combination"],
  ["shield", "buckler", "aegis", "ward", "defense", "armor"],
  [
    "sword",
    "blade",
    "weapon",
    "arms",
    "iron_sword",
    "rapier",
    "dagger",
    "sabre",
    "scimitar",
    "broadsword",
    "knife",
    "shortsword",
    "longsword",
    "claymore",
    "falchion",
    "machete",
  ],
  ["altar", "shrine", "pedestal", "plinth", "platform", "dais", "table", "slab", "monument"],
  ["crown", "coronet", "diadem", "tiara", "wreath", "circlet", "headpiece", "helmet", "helm"],
  [
    "agent",
    "contractor",
    "handler",
    "guildmaster",
    "merchant",
    "vendor",
    "trader",
    "dealer",
    "seller",
    "clerk",
    "shopkeeper",
    "person",
  ],
  ["staff", "wand", "rod", "pole", "sceptre", "scepter", "cane", "baton", "cudgel"],
  ["boots", "shoes", "footwear", "sandals", "slippers", "sabaton", "sabatons", "greaves", "footgear"],
  ["backpack", "knapsack", "bag", "pouch", "sack", "satchel", "pack", "haversack", "tote"],
  ["mound", "earth", "dirt", "soil", "ground", "clay", "dust", "gravel", "sand", "mud", "land", "loam", "peat"],
  ["glade", "clearing", "meadow", "lawn", "pasture", "field", "flat", "opening", "plain"],
  ["elf", "elven", "ranger"],
  ["up", "cliff", "cliffside", "rocks", "peak", "summit", "slope", "mountaineering"],
  ["west", "forest", "woods", "jungle", "canopy", "deep_forest"],
  ["east", "glade", "meadow", "pasture", "hidden_glade"],
];

function areSynonyms(word1: string, word2: string): boolean {
  const w1 = word1.toLowerCase();
  const w2 = word2.toLowerCase();
  if (w1 === w2) return true;
  for (const group of SYNONYM_GROUPS) {
    if (group.includes(w1) && group.includes(w2)) {
      return true;
    }
  }
  return false;
}

function getNounMatchStrength(userNoun: string, cmdNouns: string[], cmdTokens: string[]): number {
  const noiseWords = ["a", "an", "the", "of", "on", "with", "to", "from", "at", "in", "into", "and", "or"];
  const un = userNoun.toLowerCase();
  if (noiseWords.includes(un)) return 0;

  // 1. Exact match (strongest)
  for (const cn of cmdNouns) {
    if (un === cn.toLowerCase()) return 1.0;
  }
  for (const ct of cmdTokens) {
    const ctLower = ct.toLowerCase();
    if (noiseWords.includes(ctLower)) continue;
    if (un === ctLower) return 1.0;
  }

  // 2. Synonym match
  for (const cn of cmdNouns) {
    if (areSynonyms(un, cn)) return 0.8;
  }
  for (const ct of cmdTokens) {
    const ctLower = ct.toLowerCase();
    if (noiseWords.includes(ctLower)) continue;
    if (areSynonyms(un, ctLower)) return 0.8;
  }

  // 3. Substring match
  if (un.length >= 3) {
    for (const cn of cmdNouns) {
      if (cn.includes(un) || un.includes(cn)) return 0.6;
    }
    for (const ct of cmdTokens) {
      const ctLower = ct.toLowerCase();
      if (noiseWords.includes(ctLower)) continue;
      if (ctLower.includes(un) || un.includes(ctLower)) return 0.6;
    }
  }

  // 4. Levenshtein fuzzy match
  for (const cn of cmdNouns) {
    if (cn.length >= 4) {
      const dist = levenshtein(un, cn);
      const maxDist = cn.length >= 6 ? 2 : 1;
      if (dist <= maxDist) return 0.4;
    }
  }
  for (const ct of cmdTokens) {
    const ctLower = ct.toLowerCase();
    if (noiseWords.includes(ctLower)) continue;
    if (ctLower.length >= 4) {
      const dist = levenshtein(un, ctLower);
      const maxDist = ctLower.length >= 6 ? 2 : 1;
      if (dist <= maxDist) return 0.4;
    }
  }

  return 0;
}

let cachedStaticVocab: Set<string> | null = null;
function getStaticVocab(): Set<string> {
  if (cachedStaticVocab) return cachedStaticVocab;
  cachedStaticVocab = new Set<string>();
  for (const key of Object.keys(VERB_CATEGORIES)) {
    const words = key.split(/\s+/);
    for (const w of words) {
      if (w) cachedStaticVocab.add(w);
    }
  }
  return cachedStaticVocab;
}

export function mapCommand(rawInput: string, availableActions: AvailableAction[]): { action?: Action; error?: string } {
  // Clean raw input (lowercase, remove punctuation, trim)
  const cleanInput = rawInput
    .trim()
    .toLowerCase()
    .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g, "");

  if (!cleanInput) {
    return { error: "I don't understand that command. Please specify an action." };
  }

  // Tokenize helper to filter noise words from nouns
  const tokenizeNouns = (str: string): string[] => {
    return str
      .split(/\s+/)
      .filter(
        (w) => w && !["a", "an", "the", "of", "on", "with", "to", "from", "at", "in", "into", "and", "or"].includes(w)
      );
  };

  // Build local vocabulary of valid words
  const vocab = new Set<string>(getStaticVocab());
  for (const action of availableActions) {
    const words = action.command
      .toLowerCase()
      .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g, "")
      .split(/\s+/);
    for (const w of words) {
      if (w) vocab.add(w);
    }
  }

  const spellingCorrect = (inputStr: string): string => {
    const words = inputStr.split(/\s+/);
    const correctedWords = words.map((word) => {
      if (
        word.length < 3 ||
        ["a", "an", "the", "of", "on", "with", "to", "from", "at", "in", "into"].includes(word) ||
        vocab.has(word)
      ) {
        return word;
      }

      let bestWord = word;
      let bestDist = Infinity;
      for (const vocabWord of vocab) {
        const dist = levenshtein(word, vocabWord);
        if (dist < bestDist) {
          bestDist = dist;
          bestWord = vocabWord;
        }
      }

      const maxAllowedDist = word.length <= 3 ? 1 : word.length >= 6 ? 2 : 1;
      if (bestDist <= maxAllowedDist) {
        return bestWord;
      }
      return word;
    });
    return correctedWords.join(" ");
  };

  const getSpellFromVerb = (verb: string): string | undefined => {
    const v = verb.toLowerCase();
    if (
      v.includes("fireball") ||
      v.includes("flame") ||
      v.includes("fire") ||
      v.includes("burn") ||
      v.includes("ignite") ||
      v.includes("scorch") ||
      v.includes("incinerate") ||
      v.includes("singe") ||
      v.includes("combust")
    )
      return "fireball";
    if (
      v.includes("freeze") ||
      v.includes("ice") ||
      v.includes("frost") ||
      v.includes("chill") ||
      v.includes("frozen") ||
      v.includes("shiver") ||
      v.includes("numb") ||
      v.includes("glaciate")
    )
      return "freeze";
    if (
      v.includes("lightning") ||
      v.includes("zap") ||
      v.includes("shock") ||
      v.includes("electrocut") ||
      v.includes("electrocute") ||
      v.includes("spark") ||
      v.includes("bolt") ||
      v.includes("volt") ||
      v.includes("current") ||
      v.includes("charge")
    )
      return "lightning";
    if (
      v.includes("poison") ||
      v.includes("toxin") ||
      v.includes("venom") ||
      v.includes("infect") ||
      v.includes("toxic") ||
      v.includes("miasma") ||
      v.includes("blight") ||
      v.includes("contagion") ||
      v.includes("corrode")
    )
      return "poison";
    if (v.includes("heal") || v.includes("cure") || v.includes("restore") || v.includes("mend")) return "heal";
    if (v.includes("spell") || v.includes("magic")) return "spell";
    return undefined;
  };

  const evaluateCandidates = (inputStr: string): { action: AvailableAction; score: number }[] => {
    const normalized = normalizeCommandString(inputStr);

    // 1. Attempt exact match on standard command string
    const exactMatched = availableActions.find((a) => a.command.toLowerCase() === normalized);
    if (exactMatched) {
      return [{ action: exactMatched, score: 3.0 }];
    }

    const cleanInputStr = inputStr
      .trim()
      .toLowerCase()
      .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g, "");

    if (!cleanInputStr) {
      return [];
    }

    let userVerb = "";
    let userNounsString = "";

    for (const cv of compoundVerbs) {
      if (cleanInputStr.startsWith(cv + " ") || cleanInputStr === cv) {
        userVerb = cv;
        userNounsString = cleanInputStr.substring(cv.length).trim();
        break;
      }
    }

    if (!userVerb) {
      const firstSpace = cleanInputStr.indexOf(" ");
      if (firstSpace === -1) {
        userVerb = cleanInputStr;
        userNounsString = "";
      } else {
        userVerb = cleanInputStr.substring(0, firstSpace);
        userNounsString = cleanInputStr.substring(firstSpace + 1).trim();
      }
    }

    const userNouns = tokenizeNouns(userNounsString);

    // Normalize verb category
    const userVerbWord = userVerb.split(" ")[0];
    const userCategories = VERB_CATEGORIES[userVerb] || VERB_CATEGORIES[userVerbWord] || [];

    const candidatesList: { action: AvailableAction; score: number }[] = [];

    for (const a of availableActions) {
      const aCmdLower = a.command.toLowerCase().replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g, "");

      let cmdVerb = "";
      let cmdNounsString = "";

      for (const cv of compoundVerbs) {
        if (aCmdLower.startsWith(cv + " ") || aCmdLower === cv) {
          cmdVerb = cv;
          cmdNounsString = aCmdLower.substring(cv.length).trim();
          break;
        }
      }

      if (!cmdVerb) {
        const firstSpace = aCmdLower.indexOf(" ");
        if (firstSpace === -1) {
          cmdVerb = aCmdLower;
          cmdNounsString = "";
        } else {
          cmdVerb = aCmdLower.substring(0, firstSpace);
          cmdNounsString = aCmdLower.substring(firstSpace + 1).trim();
        }
      }

      const actionCategory = getActionCategory(a.action.type);

      // Check noun word matching
      const cmdNouns = tokenizeNouns(cmdNounsString);

      // Dynamically extract targets/npc/item from the action object to enrich matching
      const act = a.action as any;
      if (act.target && typeof act.target === "string") {
        const targetWords = act.target
          .toLowerCase()
          .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g, " ")
          .split(/\s+/);
        for (const w of targetWords) {
          if (w && !cmdNouns.includes(w)) cmdNouns.push(w);
        }
      }
      if (act.npc && typeof act.npc === "string") {
        const npcWords = act.npc
          .toLowerCase()
          .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g, " ")
          .split(/\s+/);
        for (const w of npcWords) {
          if (w && !cmdNouns.includes(w)) cmdNouns.push(w);
        }
      }
      if (act.item && typeof act.item === "string") {
        const itemWords = act.item
          .toLowerCase()
          .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?]/g, " ")
          .split(/\s+/);
        for (const w of itemWords) {
          if (w && !cmdNouns.includes(w)) cmdNouns.push(w);
        }
      }

      const cmdTokens = aCmdLower.split(/\s+/);

      let matchedNounCount = 0;
      let matchedNounStrengthSum = 0;
      for (const userNoun of userNouns) {
        const strength = getNounMatchStrength(userNoun, cmdNouns, cmdTokens);
        if (strength > 0) {
          matchedNounCount++;
          matchedNounStrengthSum += strength;
        }
      }

      const DIALOGUE_SYNONYM_GROUPS = [
        ["fight", "attack", "kill", "slay", "battle", "confront", "engage", "hit", "smash", "punch"],
        ["accept", "agree", "take"],
        [
          "report",
          "complete",
          "finish",
          "turn",
          "submit",
          "completion",
          "deliver",
          "hand",
          "give",
          "pay",
          "pass",
          "render",
          "provide",
          "return",
          "surrender",
          "yield",
          "bring",
        ],
        [
          "prestige",
          "reputation",
          "standing",
          "alliances",
          "alliance",
          "status",
          "loyalty",
          "check",
          "show",
          "view",
          "display",
        ],
        ["prestige", "check"],
        ["bye", "goodbye", "leave", "exit"],
        [
          "price",
          "cost",
          "value",
          "worth",
          "tariff",
          "fee",
          "rate",
          "charge",
          "valuation",
          "pricing",
          "price?",
          "cost?",
          "value?",
          "worth?",
          "gold",
          "coins",
          "coin",
          "money",
        ],
        [
          "buy",
          "purchase",
          "sell",
          "trade",
          "deal",
          "exchange",
          "barter",
          "acquire",
          "obtain",
          "procure",
          "vend",
          "hawk",
          "shop",
          "pay",
          "order",
          "request",
          "hire",
          "rent",
          "checkout",
        ],
        [
          "combine",
          "craft",
          "meld",
          "forge",
          "mix",
          "merge",
          "synthesize",
          "blend",
          "fuse",
          "assemble",
          "build",
          "construct",
          "fabricate",
          "make",
          "manufacture",
          "create",
          "prepare",
          "concoct",
          "transmute",
          "brew",
          "weave",
          "join",
          "unite",
          "connect",
          "link",
          "attach",
          "alloy",
          "weld",
          "fashion",
          "shape",
          "mold",
        ],
      ];

      let dialogueSemanticBoost = 0;
      for (const group of DIALOGUE_SYNONYM_GROUPS) {
        const userHasWord = userNouns.concat(userVerb.split(/\s+/)).some((w) => group.includes(w));
        const cmdHasWord = aCmdLower.split(/\s+/).some((w) => group.includes(w));
        if (userHasWord && cmdHasWord) {
          dialogueSemanticBoost = 1.5;
          break;
        }
      }

      // Check verb category compatibility
      let isFallbackMatch = false;
      let verbMatch = userCategories.includes(actionCategory);
      if (!verbMatch && (actionCategory === "ASK" || actionCategory === "TALK")) {
        // Only allow fallback for ASK/TALK if:
        // 1. User input is a topic name or has no specific non-TALK/ASK verb category (userCategories is empty or contains ASK/TALK)
        // 2. OR there is a noun match or dialogue semantic boost
        // 3. OR the user is attempting a transaction (BUY/SELL) which is handled via NPC dialogue
        const hasSpecificVerbCategory = userCategories.some((cat) => cat !== "ASK" && cat !== "TALK");
        const isTransactionVerb = userCategories.includes("BUY") || userCategories.includes("SELL");
        if (!hasSpecificVerbCategory || matchedNounCount > 0 || dialogueSemanticBoost > 0 || isTransactionVerb) {
          verbMatch = true;
          isFallbackMatch = true;
        }
      }
      if (!verbMatch) continue;

      let score = 0;
      if (actionCategory === "MOVE") {
        const direction = (a.action as any).direction;
        const hasDirection =
          direction &&
          (cleanInputStr.includes(direction.toLowerCase()) || userNouns.some((un) => areSynonyms(un, direction)));

        if (cmdNouns.length > 0) {
          if (userNouns.length > 0) {
            if (matchedNounCount === 0) {
              score = 0.1; // complete noun mismatch
            } else {
              const nounMatchRatio = matchedNounStrengthSum / userNouns.length;
              score = 1.0 + nounMatchRatio + (hasDirection ? 1.0 : 0.0);
            }
          } else {
            // Baseline matching if no user nouns given but verb matches (e.g. "climb" matching "climb down well")
            score = 1.0 - 0.2 + (hasDirection ? 1.0 : 0.0);
          }
        } else {
          // Simple directions like "go north" or verb matches
          if (hasDirection) {
            score = 2.0;
          } else if (cmdVerb.startsWith(userVerb) || userVerb.startsWith(cmdVerb)) {
            score = 1.0 - 0.2; // 0.8 baseline
          } else {
            score = userNouns.length > 0 ? 0.1 : 0.5;
          }
        }
        if (isFallbackMatch) {
          score -= 0.5;
        }
      } else {
        let scoreBase = 1.0;
        const isTransactionVerb = userCategories.includes("BUY") || userCategories.includes("SELL");
        const isNPCTarget = actionCategory === "TALK" || actionCategory === "ASK";
        if (userNouns.length > 0 && cmdNouns.length > 0) {
          if (matchedNounCount === 0) {
            if (isTransactionVerb && isNPCTarget) {
              // For transaction verbs (buy/sell), target noun is the item, which won't match NPC name.
              // Do not penalize as noun mismatch, but keep scoreBase at 1.0.
              scoreBase = 1.0;
            } else {
              scoreBase = 0.1; // complete noun mismatch
            }
          } else {
            const nounMatchRatio = matchedNounStrengthSum / userNouns.length;
            scoreBase = 1.0 + nounMatchRatio;
          }
        } else if (userNouns.length > 0 && cmdNouns.length === 0) {
          scoreBase = 0.5;
        } else if (userNouns.length === 0 && cmdNouns.length > 0) {
          scoreBase = 1.0 - 0.2; // 0.8 baseline
        }

        // Boost merchant/shop NPCs for transaction verbs
        if (isTransactionVerb && isNPCTarget) {
          const cmdLower = a.command.toLowerCase();
          if (
            cmdLower.includes("merchant") ||
            cmdLower.includes("shop") ||
            cmdLower.includes("trader") ||
            cmdLower.includes("vendor") ||
            cmdLower.includes("dealer") ||
            cmdLower.includes("seller")
          ) {
            scoreBase += 0.2;
          }
        }

        let verbBoost = 0;
        if (userNouns.length > 0) {
          if (userVerb === cmdVerb) {
            verbBoost = 0.3;
          } else {
            const userSpell = getSpellFromVerb(userVerb);
            const cmdSpell = getSpellFromVerb(cmdVerb);
            const actionSpell = (a.action as any).spell;
            if (userSpell && (userSpell === cmdSpell || userSpell === actionSpell)) {
              verbBoost = 0.2;
            } else {
              const commonPairs = [
                ["cast fireball", "cast fireball on"],
                ["cast fireball", "cast fireball at"],
                ["cast fireball", "use fireball on"],
                ["cast fireball", "shoot fireball at"],
                ["cast fireball", "hurl fireball at"],
                ["cast fireball", "throw fireball at"],
                ["cast fireball", "blast fireball at"],
                ["cast fireball", "cast flame on"],
                ["cast fireball", "cast fire on"],
                ["cast freeze", "cast freeze on"],
                ["cast freeze", "cast freeze at"],
                ["cast freeze", "use freeze on"],
                ["cast freeze", "shoot freeze at"],
                ["cast freeze", "hurl freeze at"],
                ["cast freeze", "throw freeze at"],
                ["cast freeze", "blast freeze at"],
                ["cast freeze", "cast ice on"],
                ["cast freeze", "cast frost on"],
                ["cast lightning", "cast lightning on"],
                ["cast lightning", "cast lightning at"],
                ["cast lightning", "use lightning on"],
                ["cast lightning", "shoot lightning at"],
                ["cast lightning", "hurl lightning at"],
                ["cast lightning", "throw lightning at"],
                ["cast lightning", "blast lightning at"],
                ["cast lightning", "cast shock on"],
                ["cast poison", "cast poison on"],
                ["cast poison", "cast poison at"],
                ["cast poison", "use poison on"],
                ["cast poison", "shoot poison at"],
                ["cast poison", "hurl poison at"],
                ["cast poison", "throw poison at"],
                ["cast poison", "blast poison at"],
                ["cast poison", "cast venom on"],
                ["cast heal", "cast heal on"],
                ["cast heal", "cast heal at"],
                ["cast heal", "use heal on"],
                ["cast heal", "heal self"],
                ["cast heal", "heal target"],
                ["cast heal", "restore self"],
                ["cast heal", "cure self"],
                ["look", "look at"],
                ["look", "look closely at"],
                ["inspect", "inspect closely"],
                ["take", "pick up"],
                ["take", "gather up"],
                ["take", "scoop up"],
                ["drop", "put down"],
                ["drop", "toss out"],
                ["open", "swing open"],
                ["close", "shut close"],
                ["talk", "talk to"],
                ["talk", "speak with"],
                ["talk", "chat with"],
                ["accost", "talk to"],
                ["converse", "talk to"],
                ["converse with", "talk to"],
                ["greet", "talk to"],
                ["chat", "talk to"],
                ["speak", "talk to"],
                ["address", "talk to"],
                ["hail", "talk to"],
                ["parley", "talk to"],
                ["interact", "talk to"],
                ["accost", "talk"],
                ["converse", "talk"],
                ["converse with", "talk"],
                ["greet", "talk"],
                ["chat", "talk"],
                ["speak", "talk"],
                ["address", "talk"],
                ["hail", "talk"],
                ["parley", "talk"],
                ["interact", "talk"],
                ["fight", "engage in combat with"],
                ["fight", "initiate combat with"],
                ["fight", "initiate battle with"],
                ["fight", "engage in combat with the"],
                ["fight", "engage in battle with"],
                ["fight", "engage in battle with the"],
                ["fight", "engage in a fight with"],
                ["fight", "engage in a fight with the"],
                ["fight", "engage in a brawl with"],
                ["fight", "engage in a skirmish with"],
                ["fight", "strike a blow against"],
                ["fight", "strike a blow against the"],
                ["fight", "deliver a blow to"],
                ["fight", "deliver a blow to the"],
                ["fight", "lay waste to"],
                ["fight", "lay waste to the"],
                ["fight", "finish off"],
                ["fight", "finish off the"],
                ["fight", "do battle with"],
                ["fight", "do battle with the"],
                ["fight", "wage war against"],
                ["fight", "wage war against the"],
                ["fight", "ambush"],
                ["fight", "ambush the"],
                ["fight", "backstab"],
                ["fight", "backstab the"],
                ["fight", "strike down"],
                ["fight", "strike down the"],
                ["fight", "beat down"],
                ["fight", "beat down the"],
                ["fight", "smite"],
                ["fight", "vanquish"],
                ["fight", "execute"],
                ["fight", "cleave"],
                ["fight", "pulverize"],
                ["fight", "subdue"],
                ["fight", "decimate"],
                ["fight", "annihilate"],
                ["fight", "maul"],
                ["fight", "bludgeon"],
                ["fight", "slaughter"],
                ["buy", "purchase"],
                ["buy", "acquire"],
                ["buy", "procure"],
                ["buy", "transact"],
                ["buy", "buy from"],
                ["buy", "buy from the"],
                ["buy", "purchase from"],
                ["buy", "purchase from the"],
                ["buy", "acquire from"],
                ["buy", "acquire from the"],
                ["buy", "procure from"],
                ["buy", "procure from the"],
                ["sell", "sell to"],
                ["sell", "sell to the"],
                ["sell", "vend"],
                ["sell", "vend to"],
                ["sell", "vend to the"],
                ["sell", "pawn"],
                ["sell", "pawn to"],
                ["sell", "pawn to the"],
                ["sell", "peddle"],
                ["sell", "peddle to"],
                ["sell", "peddle to the"],
                ["sell", "liquidate"],
                ["sell", "cash in"],
                ["sell", "cash in the"],
                ["sell", "exchange"],
                ["sell", "exchange the"],
                ["sell", "exchange for gold"],
                ["sell", "exchange for coins"],
                ["sell", "exchange for cash"],
                ["flee", "run away from"],
                ["flee", "scurry away from"],
                // Generic examination synonyms mapping to canonical "look at" to avoid ties with "inspect" (AF-28)
                ["examine", "look at"],
                ["x", "look at"],
                ["view", "look at"],
                ["search", "look at"],
                ["read", "look at"],
                ["peer", "look at"],
                ["stare", "look at"],
                ["observe", "look at"],
                ["scan", "look at"],
                ["check", "look at"],
                ["study", "look at"],
                ["gaze", "look at"],
                ["glance", "look at"],
                ["scrutinize", "look at"],
                ["watch", "look at"],
                ["explore", "look at"],
                ["find", "look at"],
                ["seek", "look at"],
                ["look closely", "look at"],
                ["examine closely", "look at"],
                ["look closely at", "look at"],
                ["take a look at", "look at"],
                ["gaze upon", "look at"],
                ["glance upon", "look at"],
                ["stare upon", "look at"],
                ["peer inside of", "look at"],
                ["peer into of", "look at"],
                ["peer at of", "look at"],
                ["look in to", "look at"],
                ["look inside of", "look at"],
                ["read book", "look at"],
                ["read paper", "look at"],
                ["inspect item", "look at"],
                ["examine object", "look at"],
                ["peer down into", "look at"],
                ["unlock", "crack lock on"],
                ["unlock", "disengage lock on"],
                ["unlock", "undo the lock on"],
              ];
              const hasPair = commonPairs.some(
                ([v1, v2]) =>
                  (userVerb === v1 && (cmdVerb === v2 || cmdVerb.startsWith(v2 + " "))) ||
                  (userVerb === v2 && (cmdVerb === v1 || cmdVerb.startsWith(v1 + " ")))
              );
              if (hasPair) {
                verbBoost = 0.2;
              } else if (cmdVerb.startsWith(userVerb) || userVerb.startsWith(cmdVerb)) {
                verbBoost = 0.1;
              }
            }
          }
        }

        score = scoreBase + dialogueSemanticBoost + verbBoost;
        if (isFallbackMatch) {
          const isTransactionVerb = userCategories.includes("BUY") || userCategories.includes("SELL");
          score -= isTransactionVerb ? 0.1 : 0.5; // Apply a fallback penalty to prioritize direct verb matches
        }
      }

      candidatesList.push({ action: a, score });
    }

    return candidatesList;
  };

  let candidates = evaluateCandidates(rawInput);
  if (rawInput.startsWith("add") || rawInput.startsWith("run")) {
    console.log(
      `DEBUG candidates for "${rawInput}":`,
      candidates.map((c) => ({ cmd: c.action.command, score: c.score }))
    );
  }
  candidates.sort((a, b) => b.score - a.score);

  // If no candidate score >= 0.8, try spelling correction
  if (candidates.length === 0 || candidates[0].score < 0.8) {
    const corrected = spellingCorrect(cleanInput);
    if (corrected !== cleanInput) {
      const correctedCandidates = evaluateCandidates(corrected);
      correctedCandidates.sort((a, b) => b.score - a.score);
      if (correctedCandidates.length > 0 && correctedCandidates[0].score >= 0.8) {
        candidates = correctedCandidates;
      }
    }
  }

  if (candidates.length > 0 && candidates[0].score >= 0.8) {
    const topScore = candidates[0].score;
    // Filter candidates within 0.15 of the top score
    const closeCandidates = candidates.filter((c) => c.score >= topScore - 0.15);

    // Keep distinct physical actions
    const distinctActions: typeof closeCandidates = [];
    for (const c of closeCandidates) {
      if (!distinctActions.some((d) => isSameAction(d.action.action, c.action.action))) {
        distinctActions.push(c);
      }
    }

    if (distinctActions.length > 1) {
      const commandList = distinctActions.map((c) => `'${c.action.command}'`).join(" or ");
      return { error: `Did you mean ${commandList}?` };
    }

    return { action: candidates[0].action.action };
  }

  // 3. Friendly error reporting with valid verbs/commands list
  const uniqueVerbs = new Set<string>();
  availableActions.forEach((a) => {
    const verb = a.command.split(" ")[0];
    uniqueVerbs.add(verb);
  });

  const validVerbs = Array.from(uniqueVerbs).join(", ");
  const errorMsg = `I don't understand that command. Try using one of these actions: ${validVerbs}. (Or type 'look' to see your surroundings).`;
  return { error: errorMsg };
}

import { registerSynonyms1 } from "./command_map_synonyms_1.js";
import { registerSynonyms2 } from "./command_map_synonyms_2.js";

registerSynonyms1(VERB_CATEGORIES, compoundVerbs, SYNONYM_GROUPS);
registerSynonyms2(VERB_CATEGORIES, compoundVerbs, SYNONYM_GROUPS);

compoundVerbs.sort((a, b) => b.length - a.length);
