/**
 * @module playtest/types
 *
 * Core type definitions for the AdventureForge blind playtesting system.
 *
 * The playtesting system uses LLM-driven personas to automatically play through
 * generated adventure packs, recording hard metrics and conducting post-game
 * interviews to surface quality issues before human players encounter them.
 */

// ─── Persona ────────────────────────────────────────────────────────────────

/**
 * Defines a playtesting persona — a behavioural archetype that guides how
 * the LLM plays through an adventure pack.
 *
 * Each persona has a distinct play style, priority focus, and threshold for
 * when they would realistically quit the game. This diversity ensures broad
 * coverage of potential player experiences.
 */
export type PlaytestPersona = {
  /** Unique identifier for the persona (e.g. `"explorer"`, `"speedrunner"`). */
  id: string;
  /** Human-readable display name (e.g. `"Explorer"`, `"Speedrunner"`). */
  name: string;
  /** Description of how this persona plays — injected into the LLM prompt. */
  style: string;
  /** What this persona focuses on and prioritises during play. */
  priority: string;
  /** Conditions under which this persona would give up and stop playing. */
  quitThreshold: string;
};

// ─── Hard Metrics ───────────────────────────────────────────────────────────

/**
 * Hard metrics recorded automatically during a single playtest session.
 *
 * These are objective, machine-collected numbers — no LLM judgement involved.
 * Every field is deterministic and reproducible from the turn-by-turn trace.
 */
export type PlaytestMetrics = {
  /** Unique identifier for this playtest session. */
  sessionId: string;
  /** ISO 8601 timestamp of when the session started. */
  timestamp: string;
  /** Identifier of the adventure pack being tested. */
  packId: string;
  /** Identifier of the persona used for this session. */
  persona: string;
  /** LLM model identifier used for the player agent. */
  modelUsed: string;
  /** Total number of turns (player actions) taken. */
  totalSteps: number;
  /** Wall-clock duration of the session in seconds. */
  playtimeSeconds: number;
  /**
   * How the session ended:
   * - `completed` — reached a defined ending
   * - `stuck` — unable to make progress
   * - `died` — player character died
   * - `quit_confused` — persona quit due to confusion
   * - `quit_bored` — persona quit due to boredom
   * - `max_steps` — hit the maximum step limit
   */
  outcome:
    | "completed"
    | "stuck"
    | "died"
    | "quit_confused"
    | "quit_bored"
    | "max_steps";
  /** Identifier of the ending reached, or `null` if none. */
  endingReached: string | null;
  /** Number of times the player character died during the session. */
  deaths: number;
  /** Estimated progress through the adventure as a percentage (0–100). */
  progressPct: number;
  /** Number of unique rooms the player visited. */
  uniqueRoomsVisited: number;
  /** Total number of rooms available in the adventure pack. */
  totalRoomsAvailable: number;
  /** Number of unique items the player interacted with. */
  uniqueItemsUsed: number;
  /** Number of NPC dialogue trees completed. */
  npcDialoguesCompleted: number;
  /** Number of puzzles successfully solved. */
  puzzlesSolved: number;
  /** Number of puzzles the player encountered (attempted or observed). */
  puzzlesEncountered: number;
  /** Number of player actions that the parser rejected as invalid. */
  actionsRejected: number;
  /** Number of consecutive turns where no progress was made. */
  turnsStuck: number;
  /** Number of times the player revisited a previously visited room. */
  backtrackCount: number;
  /** Number of times the player explicitly asked for help. */
  helpRequested: number;
  /** Path to the full turn-by-turn trace file for this session. */
  traceFile: string;
};

// ─── Post-Game Interview ────────────────────────────────────────────────────

/**
 * Structured answers to the 10 post-game interview questions.
 *
 * After a playtest session completes, the persona is asked these questions
 * in-character to capture subjective quality signals that hard metrics miss.
 * Each answer is a free-text string generated by the LLM in the persona's voice.
 */
export type PlaytestInterview = {
  /** Did you have fun? Yes/no and why. */
  q01_fun: string;
  /** What did you enjoy most? */
  q02_best: string;
  /** What did you dislike most? */
  q03_worst: string;
  /** If you could change ONE thing, what would it be? */
  q04_one_change: string;
  /** Were you ever confused about what to do next? */
  q05_confused: string;
  /** Did the game understand your commands? */
  q06_commands: string;
  /** Did the story make sense? */
  q07_story: string;
  /** How did the game end for you? */
  q08_ending: string;
  /** Was the difficulty right? */
  q09_difficulty: string;
  /** Would you play this game again or recommend it? */
  q10_recommend: string;
};

// ─── Session Result ─────────────────────────────────────────────────────────

/**
 * Combined output for a single playtest session — hard metrics plus the
 * post-game interview answers. This is the primary data structure persisted
 * to disk and consumed by downstream analysis.
 */
export type PlaytestSessionResult = PlaytestMetrics & {
  /** Post-game interview answers from the persona. */
  interview: PlaytestInterview;
};

// ─── Interview Questions ────────────────────────────────────────────────────

/**
 * A single interview question entry, mapping a {@link PlaytestInterview} key
 * to the full question text presented to the persona.
 */
export type InterviewQuestionEntry = {
  /** The key in {@link PlaytestInterview} this question populates. */
  key: keyof PlaytestInterview;
  /** The full question text to present to the persona. */
  question: string;
};

/**
 * The 10 post-game interview questions asked to every persona after a
 * playtest session. Questions are designed to elicit actionable feedback
 * across fun factor, UX friction, narrative quality, and overall polish.
 */
export const INTERVIEW_QUESTIONS: readonly InterviewQuestionEntry[] = [
  {
    key: "q01_fun",
    question:
      "Did you have fun? Yes/no and why. What kept you playing or made you want to stop?",
  },
  {
    key: "q02_best",
    question:
      "What did you enjoy most? The single best moment or feature.",
  },
  {
    key: "q03_worst",
    question:
      "What did you dislike most? The single worst moment or frustration.",
  },
  {
    key: "q04_one_change",
    question:
      "If you could change ONE thing about this game, what would it be?",
  },
  {
    key: "q05_confused",
    question:
      "Were you ever confused about what to do next? Where? For how long? What did you try?",
  },
  {
    key: "q06_commands",
    question:
      "Did the game understand your commands? Any times you typed something reasonable and got rejected?",
  },
  {
    key: "q07_story",
    question:
      "Did the story make sense? Could you follow what was happening and why?",
  },
  {
    key: "q08_ending",
    question:
      "How did the game end for you? Was the ending satisfying, abrupt, or confusing?",
  },
  {
    key: "q09_difficulty",
    question:
      "Was the difficulty right? Too easy, too hard, or just right? Any specific puzzle that was unfair?",
  },
  {
    key: "q10_recommend",
    question:
      "Would you play this game again or recommend it? Why or why not?",
  },
] as const;

// ─── Turn Log ───────────────────────────────────────────────────────────────

/**
 * A single turn in the playtest trace log.
 *
 * Captures the full context of one player action: what room they were in,
 * what they did, what happened, and why the persona chose that action.
 * The sequence of {@link PlaytestTurnLog} entries forms the complete
 * replayable trace for a session.
 */
export type PlaytestTurnLog = {
  /** 1-indexed step number within the session. */
  step: number;
  /** Identifier of the room the player was in when this action was taken. */
  roomId: string;
  /** The action the persona chose to take (e.g. `"open chest"`, `"go north"`). */
  action: string;
  /** The game's response to the action. */
  observation: string;
  /** Whether the action was rejected by the parser as invalid. */
  wasRejected: boolean;
  /** The persona's reasoning for choosing this action (chain-of-thought). */
  reasonForChoice: string;
};
