import { z } from "zod";
import { GameState } from "./state.js";
import { GameEvent } from "./events.js";
import { PureRand } from "./rng.js";

export const EffectSchema = z.union([
  z.object({ set_flag: z.string() }),
  z.object({ clear_flag: z.string() }),
  z.object({ add_item: z.string() }),
  z.object({ remove_item: z.string() }),
  z.object({
    set_var: z.object({
      name: z.string(),
      value: z.number(),
    }),
  }),
  z.object({
    inc_var: z.object({
      name: z.string(),
      by: z.number(),
    }),
  }),
  z.object({
    dec_var: z.object({
      name: z.string(),
      by: z.number(),
    }),
  }),
  z.object({ add_journal: z.string() }),
  z.object({ goto: z.string() }),
  z.object({
    unlock_exit: z.object({
      from: z.string(),
      to: z.string(),
    }),
  }),
  z.object({ open_object: z.string() }),
  z.object({
    set_object_locked: z.object({
      id: z.string(),
      locked: z.boolean(),
    }),
  }),
  z.object({ narrate: z.string() }),
  z.object({ end_game: z.string() }),
  z.object({
    roll_skill_check: z.object({
      skill: z.string(),
      difficulty: z.number(),
      success_flag: z.string(),
    }),
  }),
  z.object({
    start_combat: z.object({
      npc_id: z.string(),
    }),
  }),
  z.object({
    damage_player: z.object({
      by: z.number(),
      msg: z.string().optional(),
    }),
  }),
  z.object({
    heal_player: z.object({
      by: z.number(),
      msg: z.string().optional(),
    }),
  }),
]);

export type Effect = z.infer<typeof EffectSchema>;

/**
 * Pure function to apply a single effect to a GameState.
 * Returns the brand-new state and the event generated by the transition.
 */
export function applyEffect(state: GameState, effect: Effect): { state: GameState; event: GameEvent } {
  // Perform a shallow clone of high-level state, deep cloning maps where necessary
  const newState = {
    ...state,
    flags: { ...state.flags },
    vars: { ...state.vars },
    inventory: [...state.inventory],
    objectState: { ...state.objectState },
    journal: [...state.journal],
    visited: { ...state.visited },
  };

  if ("set_flag" in effect) {
    const flag = effect.set_flag;
    newState.flags[flag] = true;
    return {
      state: newState,
      event: { type: "state_change", effect: "set_flag", flag },
    };
  }

  if ("clear_flag" in effect) {
    const flag = effect.clear_flag;
    newState.flags[flag] = false;
    return {
      state: newState,
      event: { type: "state_change", effect: "clear_flag", flag },
    };
  }

  if ("add_item" in effect) {
    const item = effect.add_item;
    if (!newState.inventory.includes(item)) {
      newState.inventory.push(item);
    }
    const currentObj = newState.objectState[item] ?? {};
    newState.objectState[item] = {
      ...currentObj,
      takenBy: "player",
    };
    return {
      state: newState,
      event: { type: "take", item },
    };
  }

  if ("remove_item" in effect) {
    const item = effect.remove_item;
    newState.inventory = newState.inventory.filter((i) => i !== item);
    const currentObj = newState.objectState[item] ?? {};
    newState.objectState[item] = {
      ...currentObj,
      takenBy: "destroyed",
    };
    return {
      state: newState,
      event: { type: "drop", item },
    };
  }

  if ("set_var" in effect) {
    const { name, value } = effect.set_var;
    newState.vars[name] = value;
    return {
      state: newState,
      event: { type: "state_change", effect: "set_var", variable: name, value },
    };
  }

  if ("inc_var" in effect) {
    const { name, by } = effect.inc_var;
    const oldVal = newState.vars[name] ?? 0;
    const newVal = oldVal + by;
    newState.vars[name] = newVal;
    return {
      state: newState,
      event: { type: "state_change", effect: "inc_var", variable: name, value: newVal },
    };
  }

  if ("dec_var" in effect) {
    const { name, by } = effect.dec_var;
    const oldVal = newState.vars[name] ?? 0;
    const newVal = oldVal - by;
    newState.vars[name] = newVal;
    return {
      state: newState,
      event: { type: "state_change", effect: "dec_var", variable: name, value: newVal },
    };
  }

  if ("add_journal" in effect) {
    const text = effect.add_journal;
    newState.journal.push(text);
    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("goto" in effect) {
    const sceneId = effect.goto;
    newState.current = sceneId;
    newState.visited[sceneId] = true;
    return {
      state: newState,
      event: { type: "state_change", effect: "goto", value: sceneId },
    };
  }

  if ("unlock_exit" in effect) {
    const { from, to } = effect.unlock_exit;
    // We register the unlocked path in flags for simple pure tracking in v1
    newState.flags[`exit_unlocked_${from}_to_${to}`] = true;
    return {
      state: newState,
      event: { type: "unlock_exit", from, to },
    };
  }

  if ("open_object" in effect) {
    const objectId = effect.open_object;
    const currentObj = newState.objectState[objectId] ?? {};
    newState.objectState[objectId] = {
      ...currentObj,
      open: true,
    };
    return {
      state: newState,
      event: { type: "open_object", objectId },
    };
  }

  if ("set_object_locked" in effect) {
    const { id, locked } = effect.set_object_locked;
    const currentObj = newState.objectState[id] ?? {};
    newState.objectState[id] = {
      ...currentObj,
      locked,
    };
    return {
      state: newState,
      event: { type: "state_change", effect: "set_object_locked", flag: id, value: locked },
    };
  }

  if ("narrate" in effect) {
    const text = effect.narrate;
    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("end_game" in effect) {
    const endingId = effect.end_game;
    newState.ended = true;
    newState.endingId = endingId;
    return {
      state: newState,
      event: { type: "ending", endingId, title: "Game Over", text: "" },
    };
  }

  if ("roll_skill_check" in effect) {
    const { skill, difficulty, success_flag } = effect.roll_skill_check;
    const skillVal = newState.vars[skill] ?? 0;
    const { value: roll, nextSeed } = PureRand.nextInt(newState.seed, 1, 20);
    newState.seed = nextSeed;
    const total = roll + skillVal;
    const success = total >= difficulty;
    newState.flags[success_flag] = success;

    const msg = `[Skill Check] Rolling ${skill.toUpperCase()} (Difficulty: ${difficulty}): Rolled ${roll} + Skill ${skillVal} = ${total}. ` +
                (success ? "🟢 SUCCESS!" : "🔴 FAILURE!");
    newState.journal.push(msg);

    return {
      state: newState,
      event: { type: "narration", text: msg },
    };
  }

  if ("start_combat" in effect) {
    const { npc_id } = effect.start_combat;
    newState.flags[`in_combat_with_${npc_id}`] = true;
    newState.flags[`in_dialogue_with_${npc_id}`] = false;
    return {
      state: newState,
      event: { type: "state_change", effect: "start_combat", flag: npc_id },
    };
  }

  if ("damage_player" in effect) {
    const { by, msg } = effect.damage_player;
    const currentHp = newState.vars["hp"] ?? 20;
    const newHp = Math.max(0, currentHp - by);
    newState.vars["hp"] = newHp;

    const text = msg ?? `You take ${by} damage! (HP: ${newHp}/${newState.vars["max_hp"] ?? 20})`;
    if (newHp <= 0) {
      newState.ended = true;
      newState.endingId = "ending_died_in_combat";
    }

    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("heal_player" in effect) {
    const { by, msg } = effect.heal_player;
    const currentHp = newState.vars["hp"] ?? 20;
    const maxHp = newState.vars["max_hp"] ?? 20;
    const newHp = Math.min(maxHp, currentHp + by);
    newState.vars["hp"] = newHp;

    const text = msg ?? `You are healed for ${by} points. (HP: ${newHp}/${maxHp})`;

    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  throw new Error(`Unknown effect type: ${JSON.stringify(effect)}`);
}

/**
 * Pure function to apply a list of effects to a GameState sequentially.
 */
export function applyEffects(
  state: GameState,
  effects?: Effect[]
): { state: GameState; events: GameEvent[] } {
  if (!effects || effects.length === 0) {
    return { state, events: [] };
  }

  let currState = state;
  const events: GameEvent[] = [];

  for (const eff of effects) {
    const res = applyEffect(currState, eff);
    currState = res.state;
    events.push(res.event);
  }

  return { state: currState, events };
}
