import { z } from "zod";
import { GameState, cloneMerchantInventories } from "./state.js";
import { GameEvent } from "./events.js";
import { PureRand } from "./rng.js";
import {
  calculateTradePrice,
  checkReputationTrade,
  getMerchantGold,
  getContrabandInInventory,
  getPlayerAlignedFactions,
  isRivalFaction,
} from "./economy.js";

export const EffectSchema = z.union([
  z.object({ set_flag: z.string() }),
  z.object({ clear_flag: z.string() }),
  z.object({ add_item: z.string() }),
  z.object({ remove_item: z.string() }),
  z.object({
    change_weather: z.object({
      weather: z.string().optional(),
      temperature: z.string().optional(),
      wind: z.string().optional(),
    }),
  }),
  z.object({
    set_var: z.object({
      name: z.string(),
      value: z.number(),
    }),
  }),
  z.object({
    inc_var: z.object({
      name: z.string(),
      by: z.number(),
    }),
  }),
  z.object({
    dec_var: z.object({
      name: z.string(),
      by: z.number(),
    }),
  }),
  z.object({ add_journal: z.string() }),
  z.object({ goto: z.string() }),
  z.object({
    unlock_exit: z.object({
      from: z.string(),
      to: z.string(),
    }),
  }),
  z.object({ open_object: z.string() }),
  z.object({
    set_object_locked: z.object({
      id: z.string(),
      locked: z.boolean(),
    }),
  }),
  z.object({ narrate: z.string() }),
  z.object({ end_game: z.string() }),
  z.object({
    roll_skill_check: z.object({
      skill: z.string(),
      difficulty: z.number(),
      success_flag: z.string(),
    }),
  }),
  z.object({
    start_combat: z.object({
      npc_id: z.string(),
    }),
  }),
  z.object({
    damage_player: z.object({
      by: z.number(),
      msg: z.string().optional(),
    }),
  }),
  z.object({
    heal_player: z.object({
      by: z.number(),
      msg: z.string().optional(),
    }),
  }),
  z.object({
    generate_procedural_room: z.object({
      direction: z.string(),
      to_id: z.string(),
      name: z.string().optional(),
      description: z.string().optional(),
      template_id: z.string().optional(),
    }),
  }),
  z.object({
    trade_item: z.object({
      give_item: z.string().optional(),
      give_gold: z.number().optional(),
      receive_item: z.string().optional(),
      receive_gold: z.number().optional(),
      fail_msg: z.string().optional(),
      success_msg: z.string().optional(),
    }),
  }),
  z.object({
    npc_trade: z.object({
      npc_id: z.string(),
      action: z.enum(["buy", "sell", "stock"]),
      item: z.string().optional(),
      possible_items: z.array(z.string()).optional(),
      cost: z.number().optional(),
      success_msg: z.string().optional(),
      fail_msg: z.string().optional(),
      min_rep: z.number().optional(),
    }),
  }),
  z.object({
    change_reputation: z.object({
      npc_id: z.string(),
      by: z.number(),
    }),
  }),
  z.object({
    change_faction_reputation: z.object({
      faction_id: z.string(),
      by: z.number(),
    }),
  }),
  z.object({
    accept_guild_contract: z.object({
      id: z.string(),
      guild: z.string(),
      type: z.enum(["smuggling", "enforcement"]),
      target: z.string(),
      target_room: z.string().optional(),
      reward_gold: z.number(),
      reward_prestige: z.number(),
    }),
  }),
  z.object({
    complete_guild_contract: z.object({
      id: z.string(),
    }),
  }),
  z.object({
    add_guild_prestige: z.object({
      guild: z.string(),
      value: z.number(),
    }),
  }),
  z.object({
    declare_alliance: z.object({
      faction_a: z.string(),
      faction_b: z.string(),
      relationship: z.enum(["allied", "hostile", "neutral"]),
    }),
  }),
  z.object({
    declare_war: z.object({
      faction_a: z.string(),
      faction_b: z.string(),
      war: z.boolean(),
    }),
  }),
  z.object({
    claim_territory: z.object({
      room_id: z.string(),
      faction_id: z.string(),
    }),
  }),
]);

export type Effect =
  | z.infer<typeof EffectSchema>
  | {
      change_faction_reputation: {
        faction_id: string;
        by: number;
      };
    }
  | {
      accept_guild_contract: {
        id: string;
        guild: string;
        type: "smuggling" | "enforcement";
        target: string;
        target_room?: string;
        reward_gold: number;
        reward_prestige: number;
      };
    }
  | {
      complete_guild_contract: {
        id: string;
      };
    }
  | {
      add_guild_prestige: {
        guild: string;
        value: number;
      };
    };

/**
 * Pure function to apply a single effect to a GameState.
 * Returns the brand-new state and the event generated by the transition.
 */
export function applyEffect(state: GameState, effect: Effect, pack?: any): { state: GameState; event: GameEvent } {
  // Perform a shallow clone of high-level state, deep cloning maps where necessary
  const newState = {
    ...state,
    flags: { ...state.flags },
    vars: { ...state.vars },
    inventory: [...state.inventory],
    objectState: { ...state.objectState },
    journal: [...state.journal],
    visited: { ...state.visited },
    merchantInventories: cloneMerchantInventories(state.merchantInventories),
    tradeHistory: state.tradeHistory ? [...state.tradeHistory] : undefined,
    merchantGold: state.merchantGold ? { ...state.merchantGold } : undefined,
    merchantLastRestock: state.merchantLastRestock ? { ...state.merchantLastRestock } : undefined,
    merchantLastUpdated: state.merchantLastUpdated ? { ...state.merchantLastUpdated } : undefined,
    npcRep: state.npcRep ? { ...state.npcRep } : undefined,
    factionRep: state.factionRep ? { ...state.factionRep } : undefined,
  };

  if ("set_flag" in effect) {
    const flag = effect.set_flag;
    newState.flags[flag] = true;
    return {
      state: newState,
      event: { type: "state_change", effect: "set_flag", flag },
    };
  }

  if ("clear_flag" in effect) {
    const flag = effect.clear_flag;
    newState.flags[flag] = false;
    return {
      state: newState,
      event: { type: "state_change", effect: "clear_flag", flag },
    };
  }

  if ("add_item" in effect) {
    const item = effect.add_item;
    if (!newState.inventory.includes(item)) {
      newState.inventory.push(item);
    }
    const currentObj = newState.objectState[item] ?? {};
    newState.objectState[item] = {
      ...currentObj,
      takenBy: "player",
    };
    return {
      state: newState,
      event: { type: "take", item },
    };
  }

  if ("remove_item" in effect) {
    const item = effect.remove_item;
    newState.inventory = newState.inventory.filter((i) => i !== item);
    const currentObj = newState.objectState[item] ?? {};
    newState.objectState[item] = {
      ...currentObj,
      takenBy: "destroyed",
    };
    return {
      state: newState,
      event: { type: "drop", item },
    };
  }

  if ("set_var" in effect) {
    const { name, value } = effect.set_var;
    newState.vars[name] = value;
    return {
      state: newState,
      event: { type: "state_change", effect: "set_var", variable: name, value },
    };
  }

  if ("inc_var" in effect) {
    const { name, by } = effect.inc_var;
    const oldVal = newState.vars[name] ?? 0;
    const newVal = oldVal + by;
    newState.vars[name] = newVal;
    return {
      state: newState,
      event: { type: "state_change", effect: "inc_var", variable: name, value: newVal },
    };
  }

  if ("dec_var" in effect) {
    const { name, by } = effect.dec_var;
    const oldVal = newState.vars[name] ?? 0;
    const newVal = oldVal - by;
    newState.vars[name] = newVal;
    return {
      state: newState,
      event: { type: "state_change", effect: "dec_var", variable: name, value: newVal },
    };
  }

  if ("add_journal" in effect) {
    const text = effect.add_journal;
    newState.journal.push(text);
    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("goto" in effect) {
    const sceneId = effect.goto;
    newState.current = sceneId;
    newState.visited[sceneId] = true;
    return {
      state: newState,
      event: { type: "state_change", effect: "goto", value: sceneId },
    };
  }

  if ("unlock_exit" in effect) {
    const { from, to } = effect.unlock_exit;
    // We register the unlocked path in flags for simple pure tracking in v1
    newState.flags[`exit_unlocked_${from}_to_${to}`] = true;
    return {
      state: newState,
      event: { type: "unlock_exit", from, to },
    };
  }

  if ("open_object" in effect) {
    const objectId = effect.open_object;
    const currentObj = newState.objectState[objectId] ?? {};
    newState.objectState[objectId] = {
      ...currentObj,
      open: true,
    };
    return {
      state: newState,
      event: { type: "open_object", objectId },
    };
  }

  if ("set_object_locked" in effect) {
    const { id, locked } = effect.set_object_locked;
    const currentObj = newState.objectState[id] ?? {};
    newState.objectState[id] = {
      ...currentObj,
      locked,
    };
    return {
      state: newState,
      event: { type: "state_change", effect: "set_object_locked", flag: id, value: locked },
    };
  }

  if ("narrate" in effect) {
    const text = effect.narrate;
    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("end_game" in effect) {
    const endingId = effect.end_game;
    newState.ended = true;
    newState.endingId = endingId;
    return {
      state: newState,
      event: { type: "ending", endingId, title: "Game Over", text: "" },
    };
  }

  if ("roll_skill_check" in effect) {
    const { skill, difficulty, success_flag } = effect.roll_skill_check;
    const skillVal = newState.vars[skill] ?? 0;
    const { value: roll, nextSeed } = PureRand.nextInt(newState.seed, 1, 20);
    newState.seed = nextSeed;
    const total = roll + skillVal;
    const success = total >= difficulty;
    newState.flags[success_flag] = success;

    const msg =
      `[Skill Check] Rolling ${skill.toUpperCase()} (Difficulty: ${difficulty}): Rolled ${roll} + Skill ${skillVal} = ${total}. ` +
      (success ? "🟢 SUCCESS!" : "🔴 FAILURE!");
    newState.journal.push(msg);

    return {
      state: newState,
      event: { type: "narration", text: msg },
    };
  }

  if ("start_combat" in effect) {
    const { npc_id } = effect.start_combat;
    newState.flags[`in_combat_with_${npc_id}`] = true;
    newState.flags[`in_dialogue_with_${npc_id}`] = false;
    return {
      state: newState,
      event: { type: "state_change", effect: "start_combat", flag: npc_id },
    };
  }

  if ("damage_player" in effect) {
    const { by, msg } = effect.damage_player;
    const currentHp = newState.vars["hp"] ?? 20;
    const newHp = Math.max(0, currentHp - by);
    newState.vars["hp"] = newHp;

    const text = msg ?? `You take ${by} damage! (HP: ${newHp}/${newState.vars["max_hp"] ?? 20})`;
    if (newHp <= 0) {
      newState.ended = true;
      newState.endingId = "ending_died_in_combat";
    }

    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("heal_player" in effect) {
    const { by, msg } = effect.heal_player;
    const currentHp = newState.vars["hp"] ?? 20;
    const maxHp = newState.vars["max_hp"] ?? 20;
    const newHp = Math.min(maxHp, currentHp + by);
    newState.vars["hp"] = newHp;

    const text = msg ?? `You are healed for ${by} points. (HP: ${newHp}/${maxHp})`;

    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("generate_procedural_room" in effect) {
    const { direction, to_id, name, description, template_id } = effect.generate_procedural_room;
    if (!newState.proceduralRooms) {
      newState.proceduralRooms = [];
    }

    let roomName = name;
    let roomDesc = description;
    const templateObjects: string[] = [];
    const templateNpcs: string[] = [];

    // If template_id is provided, resolve from the pack
    if (template_id && pack && pack.procedural_templates) {
      const template = pack.procedural_templates.find((t: any) => t.id === template_id);
      if (template) {
        // Deterministic room name generation
        let generatedName = "";
        const nameParts: string[] = [];
        if (template.name_prefixes && template.name_prefixes.length > 0) {
          const { value, nextSeed } = PureRand.choose<string>(newState.seed, template.name_prefixes);
          newState.seed = nextSeed;
          nameParts.push(value);
        }
        if (template.name_adjectives && template.name_adjectives.length > 0) {
          const { value, nextSeed } = PureRand.choose<string>(newState.seed, template.name_adjectives);
          newState.seed = nextSeed;
          nameParts.push(value);
        }
        if (template.name_nouns && template.name_nouns.length > 0) {
          const { value, nextSeed } = PureRand.choose<string>(newState.seed, template.name_nouns);
          newState.seed = nextSeed;
          nameParts.push(value);
        }
        if (template.name_suffixes && template.name_suffixes.length > 0) {
          const { value, nextSeed } = PureRand.choose<string>(newState.seed, template.name_suffixes);
          newState.seed = nextSeed;
          nameParts.push(value);
        }
        if (nameParts.length > 0) {
          generatedName = nameParts.join(" ");
        }

        if (generatedName) {
          roomName = generatedName;
        } else if (template.name_pool && template.name_pool.length > 0) {
          const { value: selectedName, nextSeed: s1 } = PureRand.choose(newState.seed, template.name_pool) as {
            value: string;
            nextSeed: number;
          };
          newState.seed = s1;
          roomName = selectedName;
        }

        // Deterministic room description selection
        if (template.description_pool && template.description_pool.length > 0) {
          const { value: selectedDesc, nextSeed: s2 } = PureRand.choose(newState.seed, template.description_pool) as {
            value: string;
            nextSeed: number;
          };
          newState.seed = s2;
          roomDesc = selectedDesc;
        }

        // Deterministic environment-specific description segments
        if (template.environment_descriptions && newState.environment) {
          const env = newState.environment;
          if (env.weather && template.environment_descriptions[env.weather]) {
            const pool = template.environment_descriptions[env.weather];
            if (pool.length > 0) {
              const { value: seg, nextSeed: sEnv1 } = PureRand.choose<string>(newState.seed, pool);
              newState.seed = sEnv1;
              if (seg) {
                roomDesc = roomDesc ? `${roomDesc} ${seg}` : seg;
              }
            }
          }
          if (env.temperature && template.environment_descriptions[env.temperature]) {
            const pool = template.environment_descriptions[env.temperature];
            if (pool.length > 0) {
              const { value: seg, nextSeed: sEnv2 } = PureRand.choose<string>(newState.seed, pool);
              newState.seed = sEnv2;
              if (seg) {
                roomDesc = roomDesc ? `${roomDesc} ${seg}` : seg;
              }
            }
          }
          if (env.wind && template.environment_descriptions[env.wind]) {
            const pool = template.environment_descriptions[env.wind];
            if (pool.length > 0) {
              const { value: seg, nextSeed: sEnv3 } = PureRand.choose<string>(newState.seed, pool);
              newState.seed = sEnv3;
              if (seg) {
                roomDesc = roomDesc ? `${roomDesc} ${seg}` : seg;
              }
            }
          }
        }

        // Deterministically select a possible object to spawn (legacy support)
        if (template.possible_objects && template.possible_objects.length > 0) {
          const { value: objIndex, nextSeed: s3 } = PureRand.nextInt(
            newState.seed,
            0,
            template.possible_objects.length - 1
          );
          newState.seed = s3;
          const spawnedObj = template.possible_objects[objIndex];
          if (spawnedObj) {
            templateObjects.push(spawnedObj);
          }
        }

        // Deterministically roll for dynamic item drops
        if (template.item_drops && template.item_drops.length > 0) {
          for (const drop of template.item_drops) {
            const { value: roll, nextSeed: sDrop } = PureRand.next(newState.seed);
            newState.seed = sDrop;
            if (roll <= drop.chance) {
              templateObjects.push(drop.item_id);
            }
          }
        }

        // Deterministically select a possible NPC to spawn
        if (template.possible_npcs && template.possible_npcs.length > 0) {
          const { value: npcIndex, nextSeed: s4 } = PureRand.nextInt(
            newState.seed,
            0,
            template.possible_npcs.length - 1
          );
          newState.seed = s4;
          const spawnedNpc = template.possible_npcs[npcIndex];
          if (spawnedNpc) {
            templateNpcs.push(spawnedNpc);
          }
        }
      }
    }

    // Fallbacks
    roomName = roomName || "Mysterious Chamber";
    roomDesc = roomDesc || "A room generated by mysterious forces.";

    const oppositeDirections: Record<string, string> = {
      north: "south",
      south: "north",
      east: "west",
      west: "east",
      up: "down",
      down: "up",
    };

    const oppDir = oppositeDirections[direction] || "south";

    const exists = newState.proceduralRooms.some((r: any) => r.id === to_id);
    if (!exists) {
      newState.proceduralRooms.push({
        id: to_id,
        name: roomName,
        description: roomDesc,
        objects: templateObjects,
        npcs: templateNpcs,
        exits: [{ direction: oppDir, to: state.current }],
      });
    }

    newState.flags[`procedural_exit_${state.current}_${direction}_to_${to_id}`] = true;

    const msg = `An opening appears to the ${direction}...`;
    return {
      state: newState,
      event: { type: "narration", text: msg },
    };
  }

  if ("change_weather" in effect) {
    const { weather, temperature, wind } = effect.change_weather;
    const currentEnv = newState.environment || {
      weather: "clear",
      temperature: "mild",
      wind: "calm",
      lastUpdatedStep: newState.step,
    };
    newState.environment = {
      ...currentEnv,
      weather: weather ?? currentEnv.weather,
      temperature: temperature ?? currentEnv.temperature,
      wind: wind ?? currentEnv.wind ?? "calm",
      lastUpdatedStep: newState.step,
    };
    const text = `The environment changes: weather is now ${newState.environment.weather}, temperature is ${newState.environment.temperature}, wind is ${newState.environment.wind ?? "calm"}.`;
    newState.journal.push(`[Environment] ${text}`);
    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("trade_item" in effect) {
    const { give_item, give_gold, receive_item, receive_gold, fail_msg, success_msg } = effect.trade_item;

    // 1. Check item requirement
    if (give_item && !newState.inventory.includes(give_item)) {
      const text = fail_msg ?? `You don't have a ${give_item} to trade.`;
      return {
        state,
        event: { type: "narration", text },
      };
    }

    // 2. Check gold requirement
    const currentGold = newState.vars["gold"] ?? 0;
    if (give_gold && currentGold < give_gold) {
      const text = fail_msg ?? `You don't have enough gold (requires ${give_gold} gold, you have ${currentGold}).`;
      return {
        state,
        event: { type: "narration", text },
      };
    }

    // 3. Apply the trade
    if (give_item) {
      newState.inventory = newState.inventory.filter((item) => item !== give_item);
    }
    if (give_gold) {
      newState.vars["gold"] = currentGold - give_gold;
    }
    if (receive_item) {
      newState.inventory.push(receive_item);
    }
    if (receive_gold) {
      const finalGold = (newState.vars["gold"] ?? 0) + receive_gold;
      newState.vars["gold"] = finalGold;
    }

    const text = success_msg ?? `Trade completed successfully!`;
    return {
      state: newState,
      event: { type: "narration", text },
    };
  }

  if ("npc_trade" in effect) {
    const { npc_id, action, item, possible_items, cost, success_msg, fail_msg, min_rep } = effect.npc_trade;

    if (!newState.merchantInventories) {
      newState.merchantInventories = {};
    }
    if (!newState.merchantInventories[npc_id]) {
      newState.merchantInventories[npc_id] = [];
    }
    if (!newState.tradeHistory) {
      newState.tradeHistory = [];
    }

    const npcPack = pack?.npcs?.find((n: any) => n.id === npc_id);

    // Check Reputation requirement
    const repCheck = checkReputationTrade(newState, npcPack, min_rep);
    let bypassAllowed = false;

    if (!repCheck.allowed) {
      // Check if it's due to a cartel embargo or a faction rival embargo and can be bypassed by smuggling
      let isEmbargoed = false;
      if (newState.cartels && npcPack?.id) {
        for (const [cartelId, cartel] of Object.entries(newState.cartels)) {
          if (cartel.members.includes(npcPack.id)) {
            const cartelPolicy = newState.cartelPolicies?.[cartelId];
            const embargoedFactions = cartelPolicy?.embargoedFactions ?? [];
            for (const factionId of embargoedFactions) {
              const factionRep = newState.factionRep?.[factionId] ?? 0;
              if (factionRep > 0) {
                isEmbargoed = true;
                break;
              }
            }
          }
        }
      }

      if (!isEmbargoed) {
        const npcFaction = npcPack?.faction;
        const controllingFactionId = newState.territoryControl?.[newState.current];
        const merchantFaction = npcFaction || controllingFactionId;
        if (merchantFaction) {
          const playerAligned = getPlayerAlignedFactions(newState, "player");
          for (const playerFaction of playerAligned) {
            if (isRivalFaction(newState, merchantFaction, playerFaction)) {
              isEmbargoed = true;
              break;
            }
          }
        }
      }

      const contrabandItems = getContrabandInInventory(newState, pack);
      const carriesContraband = contrabandItems.length > 0;
      const hasSmugglingCapability =
        carriesContraband || (newState.vars["smuggling"] ?? 0) > 0 || (newState.vars["smuggling_skill"] ?? 0) > 0;

      if (isEmbargoed && hasSmugglingCapability) {
        // Trigger smuggling check to bypass cartel embargo!
        const { value: roll, nextSeed } = PureRand.next(newState.seed);
        newState.seed = nextSeed;

        let detectionChance = 0.4; // 40% base
        if (newState.vars["smuggling"]) {
          detectionChance -= newState.vars["smuggling"] * 0.05;
        }
        if (newState.vars["smuggling_skill"]) {
          detectionChance -= newState.vars["smuggling_skill"] * 0.05;
        }
        if (newState.flags["smuggler_cloak"] || newState.flags["smuggling_cloak"]) {
          detectionChance -= 0.15;
        }
        detectionChance = Math.max(0.05, Math.min(0.95, detectionChance));

        if (roll < detectionChance) {
          // Caught! Confiscate all contraband from player
          newState.inventory = newState.inventory.filter((itemId) => !contrabandItems.includes(itemId));

          // Decrement faction reputation
          const borderFactionId = npcPack.faction || npcPack.id;
          if (borderFactionId) {
            newState.factionRep = newState.factionRep || {};
            const currentRep = newState.factionRep[borderFactionId] ?? 0;
            newState.factionRep[borderFactionId] = currentRep - 15;
          }

          // Gold fine based on confiscated value
          let contrabandValue = 0;
          if (pack && (pack as any).objects) {
            for (const itemId of contrabandItems) {
              const obj = (pack as any).objects.find((o: any) => o.id === itemId);
              contrabandValue += obj?.cost ?? 10;
            }
          }
          const fine = Math.round(contrabandValue * 1.5) || 50;
          const currentGold = newState.vars["gold"] ?? 0;
          newState.vars["gold"] = Math.max(0, currentGold - fine);

          return {
            state: newState,
            event: {
              type: "narration",
              text:
                fail_msg ??
                `You were caught by the cartel guards smuggling trade past the embargo! All contraband was confiscated, you were fined ${fine} gold, and your reputation with the cartel was damaged.`,
            },
          };
        } else {
          // Success! Proceed with trade
          bypassAllowed = true;
          newState.journal.push(`Successfully smuggled trade past the cartel embargo with merchant ${npcPack.name}.`);
        }
      }

      if (!bypassAllowed) {
        return {
          state,
          event: { type: "narration", text: fail_msg ?? repCheck.reason ?? "Trade not allowed." },
        };
      }
    }

    if (action === "stock") {
      let stockedItem = item;
      if (!stockedItem && possible_items && possible_items.length > 0) {
        const controllingFactionId = newState.territoryControl?.[newState.current];
        const merchantFaction = npcPack?.faction || controllingFactionId;
        const playerAligned = getPlayerAlignedFactions(newState, "player");
        let factionPrestige = 0;
        if (merchantFaction) {
          const factionRepVal = newState.factionRep?.[merchantFaction];
          const guildPrestigeVal = newState.guildPrestige?.[`player-${merchantFaction}`];
          if (factionRepVal !== undefined && guildPrestigeVal !== undefined) {
            factionPrestige = Math.max(factionRepVal, guildPrestigeVal);
          } else if (factionRepVal !== undefined) {
            factionPrestige = factionRepVal;
          } else if (guildPrestigeVal !== undefined) {
            factionPrestige = guildPrestigeVal;
          }
        }

        let isAlliedToMerchantFaction = false;
        if (merchantFaction) {
          for (const pf of playerAligned) {
            if (
              newState.alliances?.[pf]?.[merchantFaction] === "allied" ||
              newState.alliances?.[merchantFaction]?.[pf] === "allied" ||
              newState.syndicateAlliances?.[pf]?.[merchantFaction] === "allied" ||
              newState.syndicateAlliances?.[merchantFaction]?.[pf] === "allied"
            ) {
              isAlliedToMerchantFaction = true;
              break;
            }
          }
        }

        const availableItems = possible_items.filter((itemKey) => {
          const obj = pack?.objects?.find((o: any) => o.id === itemKey);
          if (!obj) return true;
          if (obj.required_prestige !== undefined && factionPrestige < obj.required_prestige) {
            return false;
          }
          if (obj.required_reputation !== undefined && factionPrestige < obj.required_reputation) {
            return false;
          }
          if (obj.required_alliance === true && !isAlliedToMerchantFaction) {
            return false;
          }
          return true;
        });

        const itemsToChoose = availableItems.length > 0 ? availableItems : possible_items;
        const { value, nextSeed } = PureRand.choose(newState.seed, itemsToChoose);
        newState.seed = nextSeed;
        stockedItem = value;
      }

      if (stockedItem) {
        newState.merchantInventories[npc_id] = [...newState.merchantInventories[npc_id], stockedItem];
        newState.merchantLastUpdated = newState.merchantLastUpdated || {};
        newState.merchantLastUpdated[npc_id] = newState.step;
        newState.tradeHistory.push({
          step: newState.step,
          npcId: npc_id,
          action: "stock",
          item: stockedItem,
          gold: 0,
        });

        const currentObj = newState.objectState[stockedItem] ?? {};
        newState.objectState[stockedItem] = {
          ...currentObj,
          takenBy: "world",
        };

        const text = success_msg ?? `The merchant stocks: ${stockedItem}.`;
        return {
          state: newState,
          event: { type: "narration", text },
        };
      } else {
        const text = fail_msg ?? `No item was stocked.`;
        return {
          state: newState,
          event: { type: "narration", text },
        };
      }
    }

    if (action === "buy") {
      if (!item) {
        return {
          state,
          event: { type: "narration", text: "No item specified to buy." },
        };
      }

      const isStocked = newState.merchantInventories[npc_id].includes(item);
      if (!isStocked) {
        return {
          state,
          event: { type: "narration", text: fail_msg ?? `The merchant does not have ${item} in stock.` },
        };
      }

      const packObj = pack?.objects?.find((o: any) => o.id === item);

      // Check faction prestige and alliance requirements for dynamic item availability
      const controllingFactionId = newState.territoryControl?.[newState.current];
      const merchantFaction = npcPack?.faction || controllingFactionId;
      let factionPrestige = 0;
      if (merchantFaction) {
        const factionRepVal = newState.factionRep?.[merchantFaction];
        const guildPrestigeVal = newState.guildPrestige?.[`player-${merchantFaction}`];
        if (factionRepVal !== undefined && guildPrestigeVal !== undefined) {
          factionPrestige = Math.max(factionRepVal, guildPrestigeVal);
        } else if (factionRepVal !== undefined) {
          factionPrestige = factionRepVal;
        } else if (guildPrestigeVal !== undefined) {
          factionPrestige = guildPrestigeVal;
        }
      }

      let isAlliedToMerchantFaction = false;
      if (merchantFaction) {
        const playerAligned = getPlayerAlignedFactions(newState, "player");
        for (const pf of playerAligned) {
          if (
            newState.alliances?.[pf]?.[merchantFaction] === "allied" ||
            newState.alliances?.[merchantFaction]?.[pf] === "allied" ||
            newState.syndicateAlliances?.[pf]?.[merchantFaction] === "allied" ||
            newState.syndicateAlliances?.[merchantFaction]?.[pf] === "allied"
          ) {
            isAlliedToMerchantFaction = true;
            break;
          }
        }
      }

      if (packObj?.required_prestige !== undefined && factionPrestige < packObj.required_prestige) {
        return {
          state,
          event: {
            type: "narration",
            text: fail_msg ?? `This item requires ${packObj.required_prestige} faction prestige.`,
          },
        };
      }
      if (packObj?.required_reputation !== undefined && factionPrestige < packObj.required_reputation) {
        return {
          state,
          event: {
            type: "narration",
            text: fail_msg ?? `This item requires ${packObj.required_reputation} faction reputation.`,
          },
        };
      }
      if (packObj?.required_alliance === true && !isAlliedToMerchantFaction) {
        return {
          state,
          event: { type: "narration", text: fail_msg ?? `This item is exclusive to allied factions.` },
        };
      }

      const baseCost = cost ?? packObj?.cost ?? 10;
      const itemCost = calculateTradePrice(newState, npcPack, packObj, baseCost, true);

      const playerGold = newState.vars["gold"] ?? 0;
      if (playerGold < itemCost) {
        return {
          state,
          event: {
            type: "narration",
            text: fail_msg ?? `You don't have enough gold (requires ${itemCost} gold, you have ${playerGold}).`,
          },
        };
      }

      // Update Player Gold
      newState.vars["gold"] = playerGold - itemCost;

      // Update Merchant Gold
      const mGold = getMerchantGold(newState, npcPack);
      const maxGold = npcPack?.gold_limit;
      newState.merchantGold = newState.merchantGold || {};
      const nextMerchantGold = mGold + itemCost;
      newState.merchantGold[npc_id] = maxGold !== undefined ? Math.min(nextMerchantGold, maxGold) : nextMerchantGold;

      if (!newState.inventory.includes(item)) {
        newState.inventory.push(item);
      }
      newState.merchantInventories[npc_id] = newState.merchantInventories[npc_id].filter((i: string) => i !== item);

      newState.merchantLastUpdated = newState.merchantLastUpdated || {};
      newState.merchantLastUpdated[npc_id] = newState.step;

      const currentObj = newState.objectState[item] ?? {};
      newState.objectState[item] = {
        ...currentObj,
        takenBy: "player",
      };

      newState.tradeHistory.push({
        step: newState.step,
        npcId: npc_id,
        action: "buy",
        item,
        gold: itemCost,
      });

      const text = success_msg ?? `You bought the ${item} for ${itemCost} gold.`;
      return {
        state: newState,
        event: { type: "narration", text },
      };
    }

    if (action === "sell") {
      if (!item) {
        return {
          state,
          event: { type: "narration", text: "No item specified to sell." },
        };
      }

      const hasItem = newState.inventory.includes(item);
      if (!hasItem) {
        return {
          state,
          event: { type: "narration", text: fail_msg ?? `You don't have a ${item} to sell.` },
        };
      }

      const packObj = pack?.objects?.find((o: any) => o.id === item);
      if (packObj?.quest_critical) {
        return {
          state,
          event: { type: "narration", text: fail_msg ?? `You cannot sell quest critical item ${item}.` },
        };
      }

      const baseCost = cost ?? packObj?.cost ?? 10;
      const itemPayout = calculateTradePrice(newState, npcPack, packObj, baseCost, false);

      // Check Merchant Gold
      const mGold = getMerchantGold(newState, npcPack);
      if (mGold < itemPayout) {
        return {
          state,
          event: {
            type: "narration",
            text: fail_msg ?? `The merchant does not have enough gold (has ${mGold} gold, requires ${itemPayout}).`,
          },
        };
      }

      // Update Player Gold
      newState.inventory = newState.inventory.filter((i) => i !== item);
      newState.vars["gold"] = (newState.vars["gold"] ?? 0) + itemPayout;

      // Update Merchant Gold
      newState.merchantGold = newState.merchantGold || {};
      newState.merchantGold[npc_id] = Math.max(0, mGold - itemPayout);

      newState.merchantInventories[npc_id] = [...newState.merchantInventories[npc_id], item];

      newState.merchantLastUpdated = newState.merchantLastUpdated || {};
      newState.merchantLastUpdated[npc_id] = newState.step;

      const currentObj = newState.objectState[item] ?? {};
      newState.objectState[item] = {
        ...currentObj,
        takenBy: "world",
      };

      newState.tradeHistory.push({
        step: newState.step,
        npcId: npc_id,
        action: "sell",
        item,
        gold: itemPayout,
      });

      const text = success_msg ?? `You sold the ${item} for ${itemPayout} gold.`;
      return {
        state: newState,
        event: { type: "narration", text },
      };
    }
  }

  if ("change_reputation" in effect) {
    const { npc_id, by } = effect.change_reputation;
    newState.npcRep = newState.npcRep || {};
    const currentRep = newState.npcRep[npc_id] ?? 0;
    const finalRep = currentRep + by;
    newState.npcRep[npc_id] = finalRep;
    return {
      state: newState,
      event: { type: "state_change", effect: "change_reputation", variable: npc_id, value: finalRep },
    };
  }

  if ("change_faction_reputation" in effect) {
    const { faction_id, by } = effect.change_faction_reputation;
    newState.factionRep = newState.factionRep || {};
    const currentRep = newState.factionRep[faction_id] ?? 0;
    const finalRep = currentRep + by;
    newState.factionRep[faction_id] = finalRep;
    return {
      state: newState,
      event: { type: "state_change", effect: "change_faction_reputation", variable: faction_id, value: finalRep },
    };
  }

  if ("accept_guild_contract" in effect) {
    const { id, guild, type, target, target_room, reward_gold, reward_prestige } = effect.accept_guild_contract;
    newState.guildContracts = { ...newState.guildContracts };
    newState.guildContracts[id] = {
      id,
      guildId: guild,
      contractType: type,
      target,
      targetRoom: target_room,
      rewardGold: reward_gold,
      rewardPrestige: reward_prestige,
      status: "active",
      timestamp: newState.step,
    };
    const msg = `Accepted contract: ${id} (${type} for ${guild})`;
    newState.journal.push(msg);
    return {
      state: newState,
      event: { type: "state_change", effect: "accept_guild_contract" as any, flag: id },
    };
  }

  if ("complete_guild_contract" in effect) {
    const { id } = effect.complete_guild_contract;
    const contract = newState.guildContracts?.[id];
    if (contract && contract.status === "active") {
      newState.guildContracts = { ...newState.guildContracts };
      newState.guildContracts[id] = {
        ...contract,
        status: "completed",
      };
      if (contract.contractType === "smuggling") {
        newState.inventory = newState.inventory.filter((i) => i !== contract.target);
      }
      const currentGold = newState.vars["gold"] ?? 0;
      newState.vars["gold"] = currentGold + contract.rewardGold;
      newState.guildPrestige = { ...newState.guildPrestige };
      const key = `player-${contract.guildId}`;
      const currentPrestige = newState.guildPrestige[key] ?? 0;
      newState.guildPrestige[key] = currentPrestige + contract.rewardPrestige;

      const msg = `Completed contract: ${id}. Earned ${contract.rewardGold} gold and ${contract.rewardPrestige} prestige.`;
      newState.journal.push(msg);
      return {
        state: newState,
        event: { type: "state_change", effect: "complete_guild_contract" as any, flag: id },
      };
    }
    return {
      state: newState,
      event: { type: "state_change", effect: "complete_guild_contract" as any, flag: id },
    };
  }

  if ("add_guild_prestige" in effect) {
    const { guild, value } = effect.add_guild_prestige;
    newState.guildPrestige = { ...newState.guildPrestige };
    const key = `player-${guild}`;
    const currentPrestige = newState.guildPrestige[key] ?? 0;
    const finalPrestige = currentPrestige + value;
    newState.guildPrestige[key] = finalPrestige;
    const msg = `Your prestige with ${guild} increased by ${value} to ${finalPrestige}.`;
    newState.journal.push(msg);
    return {
      state: newState,
      event: { type: "state_change", effect: "add_guild_prestige" as any, flag: guild, value: finalPrestige },
    };
  }

  if ("declare_alliance" in effect) {
    const { faction_a, faction_b, relationship } = effect.declare_alliance;
    const alliances = state.alliances ? JSON.parse(JSON.stringify(state.alliances)) : {};
    if (!alliances[faction_a]) alliances[faction_a] = {};
    alliances[faction_a][faction_b] = relationship;
    if (!alliances[faction_b]) alliances[faction_b] = {};
    alliances[faction_b][faction_a] = relationship;
    newState.alliances = alliances;
    newState.journal.push(`[Diplomacy] Alliance between ${faction_a} and ${faction_b} set to ${relationship}.`);
    return {
      state: newState,
      event: {
        type: "state_change",
        effect: "declare_alliance" as any,
        flag: `${faction_a}_${faction_b}`,
        value: relationship as any,
      },
    };
  }

  if ("declare_war" in effect) {
    const { faction_a, faction_b, war } = effect.declare_war;
    const factionWars = state.factionWars ? JSON.parse(JSON.stringify(state.factionWars)) : {};
    if (!factionWars[faction_a]) factionWars[faction_a] = {};
    factionWars[faction_a][faction_b] = war;
    if (!factionWars[faction_b]) factionWars[faction_b] = {};
    factionWars[faction_b][faction_a] = war;
    newState.factionWars = factionWars;

    const alliances = state.alliances ? JSON.parse(JSON.stringify(state.alliances)) : {};
    const rel = war ? "hostile" : "neutral";
    if (!alliances[faction_a]) alliances[faction_a] = {};
    alliances[faction_a][faction_b] = rel;
    if (!alliances[faction_b]) alliances[faction_b] = {};
    alliances[faction_b][faction_a] = rel;
    newState.alliances = alliances;

    if (war) {
      newState.journal.push(`[War] War declared between ${faction_a} and ${faction_b}!`);
    } else {
      newState.journal.push(`[Diplomacy] Peace treaty signed between ${faction_a} and ${faction_b}.`);
    }
    return {
      state: newState,
      event: {
        type: "state_change",
        effect: "declare_war" as any,
        flag: `${faction_a}_${faction_b}`,
        value: war ? 1 : 0,
      },
    };
  }

  if ("claim_territory" in effect) {
    const { room_id, faction_id } = effect.claim_territory;
    const territoryControl = state.territoryControl ? { ...state.territoryControl } : {};
    territoryControl[room_id] = faction_id;
    newState.territoryControl = territoryControl;

    const turfGuardOutposts = state.turfGuardOutposts ? JSON.parse(JSON.stringify(state.turfGuardOutposts)) : {};
    if (turfGuardOutposts[room_id]) {
      turfGuardOutposts[room_id].syndicateId = faction_id;
      newState.turfGuardOutposts = turfGuardOutposts;
    }

    newState.journal.push(`[Sector Control] Room ${room_id} has been claimed by faction ${faction_id}.`);
    return {
      state: newState,
      event: { type: "state_change", effect: "claim_territory" as any, flag: room_id, value: faction_id as any },
    };
  }

  throw new Error(`Unknown effect type: ${JSON.stringify(effect)}`);
}

/**
 * Pure function to apply a list of effects to a GameState sequentially.
 */
export function applyEffects(
  state: GameState,
  effects?: Effect[],
  pack?: any
): { state: GameState; events: GameEvent[] } {
  if (!effects || effects.length === 0) {
    return { state, events: [] };
  }

  let currState = state;
  const events: GameEvent[] = [];

  for (const eff of effects) {
    const res = applyEffect(currState, eff, pack);
    currState = res.state;
    events.push(res.event);
  }

  return { state: currState, events };
}
